// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'entry.freezed.dart';

/// A payment card entry.
class CardEntry {
  final EntryMeta meta;
  final String cardholderName;
  final String cardNumber;
  final String expiry;
  final String cvv;
  final String? notes;

  const CardEntry({
    required this.meta,
    required this.cardholderName,
    required this.cardNumber,
    required this.expiry,
    required this.cvv,
    this.notes,
  });

  @override
  int get hashCode =>
      meta.hashCode ^
      cardholderName.hashCode ^
      cardNumber.hashCode ^
      expiry.hashCode ^
      cvv.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardEntry &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          cardholderName == other.cardholderName &&
          cardNumber == other.cardNumber &&
          expiry == other.expiry &&
          cvv == other.cvv &&
          notes == other.notes;
}

/// A fully cutom entry - user-defined fields only.
class CustomEntry {
  final EntryMeta meta;
  final String title;
  final Map<String, CustomField> fields;

  const CustomEntry({
    required this.meta,
    required this.title,
    required this.fields,
  });

  @override
  int get hashCode => meta.hashCode ^ title.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomEntry &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          title == other.title &&
          fields == other.fields;
}

/// A single user-defined key/value field on an entry.
class CustomField {
  final String label;
  final String value;

  /// If true, the value is treated as sensitive and hidden by default.
  final bool hidden;

  const CustomField({
    required this.label,
    required this.value,
    required this.hidden,
  });

  @override
  int get hashCode => label.hashCode ^ value.hashCode ^ hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomField &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          hidden == other.hidden;
}

/// Common metadata shared by every entry, regardless of type.
class EntryMeta {
  /// Stable unique identifier - never reused, even after deletion.
  final String id;

  /// ISO 8601 timestamp: when this entry was created
  final String createdAt;

  /// ISO 8601 timestamp: when this entry was last modified
  final String updatedAt;

  /// Which folder this entry belongs to (e.g. "Personal").
  final String folder;

  /// Free-form tags for filtering and organisation.
  final List<String> tags;

  /// Whether this entry appears in the favourites list.
  final bool favourite;

  const EntryMeta({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.tags,
    required this.favourite,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      tags.hashCode ^
      favourite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryMeta &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          tags == other.tags &&
          favourite == other.favourite;
}

/// A file attachement entry - stores a binary payload.
class FileEntry {
  final EntryMeta meta;
  final String filename;

  /// Raw file bytes - encrypted at rest as part of the vault body
  final Uint8List data;
  final String? notes;

  const FileEntry({
    required this.meta,
    required this.filename,
    required this.data,
    this.notes,
  });

  @override
  int get hashCode =>
      meta.hashCode ^ filename.hashCode ^ data.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntry &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          filename == other.filename &&
          data == other.data &&
          notes == other.notes;
}

/// A peronal identity entry - name, address, contact details.
class IdentityEntry {
  final EntryMeta meta;
  final String firstName;
  final String lastName;
  final String email;
  final String? phone;
  final String? address;

  const IdentityEntry({
    required this.meta,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.phone,
    this.address,
  });

  @override
  int get hashCode =>
      meta.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityEntry &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          email == other.email &&
          phone == other.phone &&
          address == other.address;
}

/// A login entry - the most common entry type
/// Stores credentials for a wehsite or application
class LoginEntry {
  /// Shared metadata (id, timestamp, folder, tags, favourite).
  final EntryMeta meta;

  /// The URL this login belongs to (e.g. "https://github.com").
  final String url;

  /// The username or email address.
  final String username;

  /// The password - always stored encrypted at rest.
  final String password;

  /// Optional free-text notes attached to this entry.
  final String? notes;

  /// User-defined extra fields (e.g. "Security question").
  final List<CustomField> customFields;

  const LoginEntry({
    required this.meta,
    required this.url,
    required this.username,
    required this.password,
    this.notes,
    required this.customFields,
  });

  @override
  int get hashCode =>
      meta.hashCode ^
      url.hashCode ^
      username.hashCode ^
      password.hashCode ^
      notes.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginEntry &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          url == other.url &&
          username == other.username &&
          password == other.password &&
          notes == other.notes &&
          customFields == other.customFields;
}

/// A secure note - free-text content with no crendential fields.
class NoteEntry {
  final EntryMeta meta;
  final String title;
  final String content;

  const NoteEntry({
    required this.meta,
    required this.title,
    required this.content,
  });

  @override
  int get hashCode => meta.hashCode ^ title.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteEntry &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          title == other.title &&
          content == other.content;
}

@freezed
sealed class VaultEntry with _$VaultEntry {
  const VaultEntry._();

  const factory VaultEntry.login(LoginEntry field0) = VaultEntry_Login;
  const factory VaultEntry.note(NoteEntry field0) = VaultEntry_Note;
  const factory VaultEntry.identity(IdentityEntry field0) = VaultEntry_Identity;
  const factory VaultEntry.card(CardEntry field0) = VaultEntry_Card;
  const factory VaultEntry.file(FileEntry field0) = VaultEntry_File;
  const factory VaultEntry.custom(CustomEntry field0) = VaultEntry_Custom;
}
