// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/entropy.dart';
import 'api/fido_bridge.dart';
import 'api/import.dart';
import 'api/passphrase_generator.dart';
import 'api/password_generator.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'api/vault.dart';
import 'api/vault_bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddedEntryItem dco_decode_added_entry_item(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CardEntryData dco_decode_box_autoadd_card_entry_data(dynamic raw);

  @protected
  CsvImportConfigData dco_decode_box_autoadd_csv_import_config_data(
    dynamic raw,
  );

  @protected
  CustomEntryData dco_decode_box_autoadd_custom_entry_data(dynamic raw);

  @protected
  FileEntryData dco_decode_box_autoadd_file_entry_data(dynamic raw);

  @protected
  IdentityEntryData dco_decode_box_autoadd_identity_entry_data(dynamic raw);

  @protected
  LoginEntryData dco_decode_box_autoadd_login_entry_data(dynamic raw);

  @protected
  NoteEntryData dco_decode_box_autoadd_note_entry_data(dynamic raw);

  @protected
  PassphraseConfig dco_decode_box_autoadd_passphrase_config(dynamic raw);

  @protected
  PasswordConfig dco_decode_box_autoadd_password_config(dynamic raw);

  @protected
  PreviousSecretData dco_decode_box_autoadd_previous_secret_data(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  VaultEntryData dco_decode_box_autoadd_vault_entry_data(dynamic raw);

  @protected
  BroughtOverItem dco_decode_brought_over_item(dynamic raw);

  @protected
  CardEntryData dco_decode_card_entry_data(dynamic raw);

  @protected
  CsvImportConfigData dco_decode_csv_import_config_data(dynamic raw);

  @protected
  CsvPreviewData dco_decode_csv_preview_data(dynamic raw);

  @protected
  CustomEntryData dco_decode_custom_entry_data(dynamic raw);

  @protected
  CustomFieldData dco_decode_custom_field_data(dynamic raw);

  @protected
  EntropyResult dco_decode_entropy_result(dynamic raw);

  @protected
  EntrySummaryData dco_decode_entry_summary_data(dynamic raw);

  @protected
  ExportArtifact dco_decode_export_artifact(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FidoCredentialData dco_decode_fido_credential_data(dynamic raw);

  @protected
  FidoHmacMatch dco_decode_fido_hmac_match(dynamic raw);

  @protected
  FidoRecordInput dco_decode_fido_record_input(dynamic raw);

  @protected
  FieldConflictItem dco_decode_field_conflict_item(dynamic raw);

  @protected
  FileEntryData dco_decode_file_entry_data(dynamic raw);

  @protected
  FolderConflictItem dco_decode_folder_conflict_item(dynamic raw);

  @protected
  GabbroImportResult dco_decode_gabbro_import_result(dynamic raw);

  @protected
  HistoryRecordData dco_decode_history_record_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IdentityEntryData dco_decode_identity_entry_data(dynamic raw);

  @protected
  ImportFailureData dco_decode_import_failure_data(dynamic raw);

  @protected
  ImportResult dco_decode_import_result(dynamic raw);

  @protected
  Language dco_decode_language(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AddedEntryItem> dco_decode_list_added_entry_item(dynamic raw);

  @protected
  List<BroughtOverItem> dco_decode_list_brought_over_item(dynamic raw);

  @protected
  List<CustomFieldData> dco_decode_list_custom_field_data(dynamic raw);

  @protected
  List<EntrySummaryData> dco_decode_list_entry_summary_data(dynamic raw);

  @protected
  List<FidoRecordInput> dco_decode_list_fido_record_input(dynamic raw);

  @protected
  List<FieldConflictItem> dco_decode_list_field_conflict_item(dynamic raw);

  @protected
  List<FolderConflictItem> dco_decode_list_folder_conflict_item(dynamic raw);

  @protected
  List<HistoryRecordData> dco_decode_list_history_record_data(dynamic raw);

  @protected
  List<ImportFailureData> dco_decode_list_import_failure_data(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<PendingDeleteItem> dco_decode_list_pending_delete_item(dynamic raw);

  @protected
  List<PendingItemDeleteItem> dco_decode_list_pending_item_delete_item(
    dynamic raw,
  );

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SkippedEntryData> dco_decode_list_skipped_entry_data(dynamic raw);

  @protected
  List<YubiKeyInitData> dco_decode_list_yubi_key_init_data(dynamic raw);

  @protected
  List<YubikeyAliasData> dco_decode_list_yubikey_alias_data(dynamic raw);

  @protected
  List<YubikeyRecordData> dco_decode_list_yubikey_record_data(dynamic raw);

  @protected
  LoginEntryData dco_decode_login_entry_data(dynamic raw);

  @protected
  MergeSummary dco_decode_merge_summary(dynamic raw);

  @protected
  NoteEntryData dco_decode_note_entry_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PreviousSecretData? dco_decode_opt_box_autoadd_previous_secret_data(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PassphraseConfig dco_decode_passphrase_config(dynamic raw);

  @protected
  PasswordConfig dco_decode_password_config(dynamic raw);

  @protected
  PendingDeleteItem dco_decode_pending_delete_item(dynamic raw);

  @protected
  PendingItemDeleteItem dco_decode_pending_item_delete_item(dynamic raw);

  @protected
  PreviousSecretData dco_decode_previous_secret_data(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SkippedEntryData dco_decode_skipped_entry_data(dynamic raw);

  @protected
  StrengthTier dco_decode_strength_tier(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultEntryData dco_decode_vault_entry_data(dynamic raw);

  @protected
  VaultHeaderData dco_decode_vault_header_data(dynamic raw);

  @protected
  YubiKeyInitData dco_decode_yubi_key_init_data(dynamic raw);

  @protected
  YubikeyAliasData dco_decode_yubikey_alias_data(dynamic raw);

  @protected
  YubikeyRecordData dco_decode_yubikey_record_data(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddedEntryItem sse_decode_added_entry_item(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CardEntryData sse_decode_box_autoadd_card_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  CsvImportConfigData sse_decode_box_autoadd_csv_import_config_data(
    SseDeserializer deserializer,
  );

  @protected
  CustomEntryData sse_decode_box_autoadd_custom_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  FileEntryData sse_decode_box_autoadd_file_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  IdentityEntryData sse_decode_box_autoadd_identity_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  LoginEntryData sse_decode_box_autoadd_login_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  NoteEntryData sse_decode_box_autoadd_note_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  PassphraseConfig sse_decode_box_autoadd_passphrase_config(
    SseDeserializer deserializer,
  );

  @protected
  PasswordConfig sse_decode_box_autoadd_password_config(
    SseDeserializer deserializer,
  );

  @protected
  PreviousSecretData sse_decode_box_autoadd_previous_secret_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VaultEntryData sse_decode_box_autoadd_vault_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  BroughtOverItem sse_decode_brought_over_item(SseDeserializer deserializer);

  @protected
  CardEntryData sse_decode_card_entry_data(SseDeserializer deserializer);

  @protected
  CsvImportConfigData sse_decode_csv_import_config_data(
    SseDeserializer deserializer,
  );

  @protected
  CsvPreviewData sse_decode_csv_preview_data(SseDeserializer deserializer);

  @protected
  CustomEntryData sse_decode_custom_entry_data(SseDeserializer deserializer);

  @protected
  CustomFieldData sse_decode_custom_field_data(SseDeserializer deserializer);

  @protected
  EntropyResult sse_decode_entropy_result(SseDeserializer deserializer);

  @protected
  EntrySummaryData sse_decode_entry_summary_data(SseDeserializer deserializer);

  @protected
  ExportArtifact sse_decode_export_artifact(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FidoCredentialData sse_decode_fido_credential_data(
    SseDeserializer deserializer,
  );

  @protected
  FidoHmacMatch sse_decode_fido_hmac_match(SseDeserializer deserializer);

  @protected
  FidoRecordInput sse_decode_fido_record_input(SseDeserializer deserializer);

  @protected
  FieldConflictItem sse_decode_field_conflict_item(
    SseDeserializer deserializer,
  );

  @protected
  FileEntryData sse_decode_file_entry_data(SseDeserializer deserializer);

  @protected
  FolderConflictItem sse_decode_folder_conflict_item(
    SseDeserializer deserializer,
  );

  @protected
  GabbroImportResult sse_decode_gabbro_import_result(
    SseDeserializer deserializer,
  );

  @protected
  HistoryRecordData sse_decode_history_record_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IdentityEntryData sse_decode_identity_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  ImportFailureData sse_decode_import_failure_data(
    SseDeserializer deserializer,
  );

  @protected
  ImportResult sse_decode_import_result(SseDeserializer deserializer);

  @protected
  Language sse_decode_language(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AddedEntryItem> sse_decode_list_added_entry_item(
    SseDeserializer deserializer,
  );

  @protected
  List<BroughtOverItem> sse_decode_list_brought_over_item(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomFieldData> sse_decode_list_custom_field_data(
    SseDeserializer deserializer,
  );

  @protected
  List<EntrySummaryData> sse_decode_list_entry_summary_data(
    SseDeserializer deserializer,
  );

  @protected
  List<FidoRecordInput> sse_decode_list_fido_record_input(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldConflictItem> sse_decode_list_field_conflict_item(
    SseDeserializer deserializer,
  );

  @protected
  List<FolderConflictItem> sse_decode_list_folder_conflict_item(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryRecordData> sse_decode_list_history_record_data(
    SseDeserializer deserializer,
  );

  @protected
  List<ImportFailureData> sse_decode_list_import_failure_data(
    SseDeserializer deserializer,
  );

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<PendingDeleteItem> sse_decode_list_pending_delete_item(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingItemDeleteItem> sse_decode_list_pending_item_delete_item(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SkippedEntryData> sse_decode_list_skipped_entry_data(
    SseDeserializer deserializer,
  );

  @protected
  List<YubiKeyInitData> sse_decode_list_yubi_key_init_data(
    SseDeserializer deserializer,
  );

  @protected
  List<YubikeyAliasData> sse_decode_list_yubikey_alias_data(
    SseDeserializer deserializer,
  );

  @protected
  List<YubikeyRecordData> sse_decode_list_yubikey_record_data(
    SseDeserializer deserializer,
  );

  @protected
  LoginEntryData sse_decode_login_entry_data(SseDeserializer deserializer);

  @protected
  MergeSummary sse_decode_merge_summary(SseDeserializer deserializer);

  @protected
  NoteEntryData sse_decode_note_entry_data(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PreviousSecretData? sse_decode_opt_box_autoadd_previous_secret_data(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PassphraseConfig sse_decode_passphrase_config(SseDeserializer deserializer);

  @protected
  PasswordConfig sse_decode_password_config(SseDeserializer deserializer);

  @protected
  PendingDeleteItem sse_decode_pending_delete_item(
    SseDeserializer deserializer,
  );

  @protected
  PendingItemDeleteItem sse_decode_pending_item_delete_item(
    SseDeserializer deserializer,
  );

  @protected
  PreviousSecretData sse_decode_previous_secret_data(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SkippedEntryData sse_decode_skipped_entry_data(SseDeserializer deserializer);

  @protected
  StrengthTier sse_decode_strength_tier(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultEntryData sse_decode_vault_entry_data(SseDeserializer deserializer);

  @protected
  VaultHeaderData sse_decode_vault_header_data(SseDeserializer deserializer);

  @protected
  YubiKeyInitData sse_decode_yubi_key_init_data(SseDeserializer deserializer);

  @protected
  YubikeyAliasData sse_decode_yubikey_alias_data(SseDeserializer deserializer);

  @protected
  YubikeyRecordData sse_decode_yubikey_record_data(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_added_entry_item(
    AddedEntryItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_card_entry_data(
    CardEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_csv_import_config_data(
    CsvImportConfigData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_custom_entry_data(
    CustomEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_entry_data(
    FileEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_identity_entry_data(
    IdentityEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_login_entry_data(
    LoginEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_note_entry_data(
    NoteEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_passphrase_config(
    PassphraseConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_password_config(
    PasswordConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_previous_secret_data(
    PreviousSecretData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vault_entry_data(
    VaultEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_brought_over_item(
    BroughtOverItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_card_entry_data(CardEntryData self, SseSerializer serializer);

  @protected
  void sse_encode_csv_import_config_data(
    CsvImportConfigData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_csv_preview_data(
    CsvPreviewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_entry_data(
    CustomEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_field_data(
    CustomFieldData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entropy_result(EntropyResult self, SseSerializer serializer);

  @protected
  void sse_encode_entry_summary_data(
    EntrySummaryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_artifact(
    ExportArtifact self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fido_credential_data(
    FidoCredentialData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fido_hmac_match(FidoHmacMatch self, SseSerializer serializer);

  @protected
  void sse_encode_fido_record_input(
    FidoRecordInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_conflict_item(
    FieldConflictItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_entry_data(FileEntryData self, SseSerializer serializer);

  @protected
  void sse_encode_folder_conflict_item(
    FolderConflictItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gabbro_import_result(
    GabbroImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_record_data(
    HistoryRecordData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_identity_entry_data(
    IdentityEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_failure_data(
    ImportFailureData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_result(ImportResult self, SseSerializer serializer);

  @protected
  void sse_encode_language(Language self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_added_entry_item(
    List<AddedEntryItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_brought_over_item(
    List<BroughtOverItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_field_data(
    List<CustomFieldData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_summary_data(
    List<EntrySummaryData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fido_record_input(
    List<FidoRecordInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_conflict_item(
    List<FieldConflictItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_folder_conflict_item(
    List<FolderConflictItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_record_data(
    List<HistoryRecordData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_import_failure_data(
    List<ImportFailureData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_delete_item(
    List<PendingDeleteItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_item_delete_item(
    List<PendingItemDeleteItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_skipped_entry_data(
    List<SkippedEntryData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_yubi_key_init_data(
    List<YubiKeyInitData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_yubikey_alias_data(
    List<YubikeyAliasData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_yubikey_record_data(
    List<YubikeyRecordData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_entry_data(
    LoginEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_summary(MergeSummary self, SseSerializer serializer);

  @protected
  void sse_encode_note_entry_data(NoteEntryData self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_previous_secret_data(
    PreviousSecretData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_passphrase_config(
    PassphraseConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_password_config(
    PasswordConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_delete_item(
    PendingDeleteItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_item_delete_item(
    PendingItemDeleteItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_previous_secret_data(
    PreviousSecretData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_skipped_entry_data(
    SkippedEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strength_tier(StrengthTier self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_entry_data(
    VaultEntryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_header_data(
    VaultHeaderData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_yubi_key_init_data(
    YubiKeyInitData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_yubikey_alias_data(
    YubikeyAliasData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_yubikey_record_data(
    YubikeyRecordData self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
