// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/entropy.dart';
import 'api/import.dart';
import 'api/passphrase_generator.dart';
import 'api/password_generator.dart';
import 'api/simple.dart';
import 'api/vault.dart';
import 'api/vault_bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1628873633;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_gabbro',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiVaultBridgeChangePassphrase({
    required List<int> oldPassphrase,
    required List<int> newPassphrase,
  });

  Future<String> crateApiVaultChronoNow();

  Future<CardEntryData> crateApiVaultCreateCardEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    String? cardName,
    required String status,
    required String cardholderName,
    required String cardNumber,
    required String expiry,
    required String cvv,
    String? creditLimit,
    String? cardAccountNumber,
    String? paymentNetwork,
    String? pin,
    String? bankName,
    String? transactionPassword,
    String? notes,
  });

  Future<CustomEntryData> crateApiVaultCreateCustomEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String title,
    required List<CustomFieldData> fields,
  });

  Future<EntrySummaryData> crateApiVaultBridgeCreateEntry({
    required VaultEntryData entry,
  });

  Future<FileEntryData> crateApiVaultCreateFileEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String filename,
    required List<int> data,
    String? notes,
  });

  Future<IdentityEntryData> crateApiVaultCreateIdentityEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String firstName,
    required String lastName,
    required String email,
    String? phone,
    String? address,
  });

  Future<LoginEntryData> crateApiVaultCreateLoginEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String title,
    required String url,
    required String username,
    required String password,
    String? notes,
    required List<CustomFieldData> customFields,
  });

  Future<NoteEntryData> crateApiVaultCreateNoteEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String title,
    required String content,
  });

  Future<void> crateApiVaultBridgeDeleteEntries({required List<String> ids});

  Future<void> crateApiVaultBridgeDeleteEntry({required String id});

  Future<void> crateApiVaultBridgeDeleteWholeVault();

  double crateApiPasswordGeneratorEntropyBits({
    required int poolSize,
    required int length,
  });

  EntropyResult crateApiEntropyEstimateEntropy({required String password});

  Future<void> crateApiVaultBridgeExportVault({required String path});

  Future<String> crateApiPassphraseGeneratorGeneratePassphrase({
    required PassphraseConfig config,
  });

  String crateApiPasswordGeneratorGeneratePassword({
    required PasswordConfig config,
  });

  VaultEntryData crateApiVaultBridgeGetEntry({required String id});

  String crateApiSimpleGreet({required String name});

  Future<BigInt> crateApiImportImportFromCsv({
    required String input,
    required CsvImportConfigData config,
  });

  Future<BigInt> crateApiVaultBridgeImportFromEnpass({required List<int> data});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiVaultBridgeInitVault({
    required List<int> passphrase,
    required String path,
  });

  List<EntrySummaryData> crateApiVaultBridgeListEntrySummaries();

  void crateApiVaultBridgeLockVault();

  Future<double> crateApiPassphraseGeneratorPassphraseEntropyBits({
    required int wordCount,
    required Language language,
  });

  CsvPreviewData crateApiImportSniffCsvFile({required String input});

  Future<void> crateApiVaultBridgeUnlockVault({
    required List<int> passphrase,
    required String path,
  });

  Future<void> crateApiVaultBridgeUpdateEntry({required VaultEntryData entry});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiVaultBridgeChangePassphrase({
    required List<int> oldPassphrase,
    required List<int> newPassphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(oldPassphrase, serializer);
          sse_encode_list_prim_u_8_loose(newPassphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeChangePassphraseConstMeta,
        argValues: [oldPassphrase, newPassphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeChangePassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "change_passphrase",
        argNames: ["oldPassphrase", "newPassphrase"],
      );

  @override
  Future<String> crateApiVaultChronoNow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultChronoNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultChronoNowConstMeta =>
      const TaskConstMeta(debugName: "chrono_now", argNames: []);

  @override
  Future<CardEntryData> crateApiVaultCreateCardEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    String? cardName,
    required String status,
    required String cardholderName,
    required String cardNumber,
    required String expiry,
    required String cvv,
    String? creditLimit,
    String? cardAccountNumber,
    String? paymentNetwork,
    String? pin,
    String? bankName,
    String? transactionPassword,
    String? notes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_bool(favourite, serializer);
          sse_encode_opt_String(cardName, serializer);
          sse_encode_String(status, serializer);
          sse_encode_String(cardholderName, serializer);
          sse_encode_String(cardNumber, serializer);
          sse_encode_String(expiry, serializer);
          sse_encode_String(cvv, serializer);
          sse_encode_opt_String(creditLimit, serializer);
          sse_encode_opt_String(cardAccountNumber, serializer);
          sse_encode_opt_String(paymentNetwork, serializer);
          sse_encode_opt_String(pin, serializer);
          sse_encode_opt_String(bankName, serializer);
          sse_encode_opt_String(transactionPassword, serializer);
          sse_encode_opt_String(notes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_card_entry_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultCreateCardEntryConstMeta,
        argValues: [
          folder,
          tags,
          favourite,
          cardName,
          status,
          cardholderName,
          cardNumber,
          expiry,
          cvv,
          creditLimit,
          cardAccountNumber,
          paymentNetwork,
          pin,
          bankName,
          transactionPassword,
          notes,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateCardEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_card_entry",
        argNames: [
          "folder",
          "tags",
          "favourite",
          "cardName",
          "status",
          "cardholderName",
          "cardNumber",
          "expiry",
          "cvv",
          "creditLimit",
          "cardAccountNumber",
          "paymentNetwork",
          "pin",
          "bankName",
          "transactionPassword",
          "notes",
        ],
      );

  @override
  Future<CustomEntryData> crateApiVaultCreateCustomEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String title,
    required List<CustomFieldData> fields,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_bool(favourite, serializer);
          sse_encode_String(title, serializer);
          sse_encode_list_custom_field_data(fields, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_custom_entry_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultCreateCustomEntryConstMeta,
        argValues: [folder, tags, favourite, title, fields],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateCustomEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_custom_entry",
        argNames: ["folder", "tags", "favourite", "title", "fields"],
      );

  @override
  Future<EntrySummaryData> crateApiVaultBridgeCreateEntry({
    required VaultEntryData entry,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_vault_entry_data(entry, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_summary_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeCreateEntryConstMeta,
        argValues: [entry],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeCreateEntryConstMeta =>
      const TaskConstMeta(debugName: "create_entry", argNames: ["entry"]);

  @override
  Future<FileEntryData> crateApiVaultCreateFileEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String filename,
    required List<int> data,
    String? notes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_bool(favourite, serializer);
          sse_encode_String(filename, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_opt_String(notes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_file_entry_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultCreateFileEntryConstMeta,
        argValues: [folder, tags, favourite, filename, data, notes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateFileEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_file_entry",
        argNames: ["folder", "tags", "favourite", "filename", "data", "notes"],
      );

  @override
  Future<IdentityEntryData> crateApiVaultCreateIdentityEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String firstName,
    required String lastName,
    required String email,
    String? phone,
    String? address,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_bool(favourite, serializer);
          sse_encode_String(firstName, serializer);
          sse_encode_String(lastName, serializer);
          sse_encode_String(email, serializer);
          sse_encode_opt_String(phone, serializer);
          sse_encode_opt_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_entry_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultCreateIdentityEntryConstMeta,
        argValues: [
          folder,
          tags,
          favourite,
          firstName,
          lastName,
          email,
          phone,
          address,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateIdentityEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_identity_entry",
        argNames: [
          "folder",
          "tags",
          "favourite",
          "firstName",
          "lastName",
          "email",
          "phone",
          "address",
        ],
      );

  @override
  Future<LoginEntryData> crateApiVaultCreateLoginEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String title,
    required String url,
    required String username,
    required String password,
    String? notes,
    required List<CustomFieldData> customFields,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_bool(favourite, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_opt_String(notes, serializer);
          sse_encode_list_custom_field_data(customFields, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_login_entry_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultCreateLoginEntryConstMeta,
        argValues: [
          folder,
          tags,
          favourite,
          title,
          url,
          username,
          password,
          notes,
          customFields,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateLoginEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_login_entry",
        argNames: [
          "folder",
          "tags",
          "favourite",
          "title",
          "url",
          "username",
          "password",
          "notes",
          "customFields",
        ],
      );

  @override
  Future<NoteEntryData> crateApiVaultCreateNoteEntry({
    required String folder,
    required List<String> tags,
    required bool favourite,
    required String title,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_bool(favourite, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_entry_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultCreateNoteEntryConstMeta,
        argValues: [folder, tags, favourite, title, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateNoteEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_note_entry",
        argNames: ["folder", "tags", "favourite", "title", "content"],
      );

  @override
  Future<void> crateApiVaultBridgeDeleteEntries({required List<String> ids}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(ids, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeDeleteEntriesConstMeta,
        argValues: [ids],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeDeleteEntriesConstMeta =>
      const TaskConstMeta(debugName: "delete_entries", argNames: ["ids"]);

  @override
  Future<void> crateApiVaultBridgeDeleteEntry({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeDeleteEntryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeDeleteEntryConstMeta =>
      const TaskConstMeta(debugName: "delete_entry", argNames: ["id"]);

  @override
  Future<void> crateApiVaultBridgeDeleteWholeVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeDeleteWholeVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeDeleteWholeVaultConstMeta =>
      const TaskConstMeta(debugName: "delete_whole_vault", argNames: []);

  @override
  double crateApiPasswordGeneratorEntropyBits({
    required int poolSize,
    required int length,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(poolSize, serializer);
          sse_encode_u_32(length, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPasswordGeneratorEntropyBitsConstMeta,
        argValues: [poolSize, length],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPasswordGeneratorEntropyBitsConstMeta =>
      const TaskConstMeta(
        debugName: "entropy_bits",
        argNames: ["poolSize", "length"],
      );

  @override
  EntropyResult crateApiEntropyEstimateEntropy({required String password}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entropy_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntropyEstimateEntropyConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntropyEstimateEntropyConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_entropy",
        argNames: ["password"],
      );

  @override
  Future<void> crateApiVaultBridgeExportVault({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeExportVaultConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeExportVaultConstMeta =>
      const TaskConstMeta(debugName: "export_vault", argNames: ["path"]);

  @override
  Future<String> crateApiPassphraseGeneratorGeneratePassphrase({
    required PassphraseConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_passphrase_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPassphraseGeneratorGeneratePassphraseConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPassphraseGeneratorGeneratePassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "generate_passphrase",
        argNames: ["config"],
      );

  @override
  String crateApiPasswordGeneratorGeneratePassword({
    required PasswordConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_password_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPasswordGeneratorGeneratePasswordConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPasswordGeneratorGeneratePasswordConstMeta =>
      const TaskConstMeta(debugName: "generate_password", argNames: ["config"]);

  @override
  VaultEntryData crateApiVaultBridgeGetEntry({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_entry_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeGetEntryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeGetEntryConstMeta =>
      const TaskConstMeta(debugName: "get_entry", argNames: ["id"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<BigInt> crateApiImportImportFromCsv({
    required String input,
    required CsvImportConfigData config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_box_autoadd_csv_import_config_data(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportImportFromCsvConstMeta,
        argValues: [input, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportImportFromCsvConstMeta =>
      const TaskConstMeta(
        debugName: "import_from_csv",
        argNames: ["input", "config"],
      );

  @override
  Future<BigInt> crateApiVaultBridgeImportFromEnpass({
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeImportFromEnpassConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeImportFromEnpassConstMeta =>
      const TaskConstMeta(debugName: "import_from_enpass", argNames: ["data"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiVaultBridgeInitVault({
    required List<int> passphrase,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeInitVaultConstMeta,
        argValues: [passphrase, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeInitVaultConstMeta =>
      const TaskConstMeta(
        debugName: "init_vault",
        argNames: ["passphrase", "path"],
      );

  @override
  List<EntrySummaryData> crateApiVaultBridgeListEntrySummaries() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_summary_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeListEntrySummariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeListEntrySummariesConstMeta =>
      const TaskConstMeta(debugName: "list_entry_summaries", argNames: []);

  @override
  void crateApiVaultBridgeLockVault() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeLockVaultConstMeta =>
      const TaskConstMeta(debugName: "lock_vault", argNames: []);

  @override
  Future<double> crateApiPassphraseGeneratorPassphraseEntropyBits({
    required int wordCount,
    required Language language,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(wordCount, serializer);
          sse_encode_language(language, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPassphraseGeneratorPassphraseEntropyBitsConstMeta,
        argValues: [wordCount, language],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPassphraseGeneratorPassphraseEntropyBitsConstMeta =>
      const TaskConstMeta(
        debugName: "passphrase_entropy_bits",
        argNames: ["wordCount", "language"],
      );

  @override
  CsvPreviewData crateApiImportSniffCsvFile({required String input}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_csv_preview_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportSniffCsvFileConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportSniffCsvFileConstMeta =>
      const TaskConstMeta(debugName: "sniff_csv_file", argNames: ["input"]);

  @override
  Future<void> crateApiVaultBridgeUnlockVault({
    required List<int> passphrase,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeUnlockVaultConstMeta,
        argValues: [passphrase, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeUnlockVaultConstMeta =>
      const TaskConstMeta(
        debugName: "unlock_vault",
        argNames: ["passphrase", "path"],
      );

  @override
  Future<void> crateApiVaultBridgeUpdateEntry({required VaultEntryData entry}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_vault_entry_data(entry, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultBridgeUpdateEntryConstMeta,
        argValues: [entry],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBridgeUpdateEntryConstMeta =>
      const TaskConstMeta(debugName: "update_entry", argNames: ["entry"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CardEntryData dco_decode_box_autoadd_card_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_card_entry_data(raw);
  }

  @protected
  CsvImportConfigData dco_decode_box_autoadd_csv_import_config_data(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_csv_import_config_data(raw);
  }

  @protected
  CustomEntryData dco_decode_box_autoadd_custom_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_custom_entry_data(raw);
  }

  @protected
  FileEntryData dco_decode_box_autoadd_file_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_file_entry_data(raw);
  }

  @protected
  IdentityEntryData dco_decode_box_autoadd_identity_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_identity_entry_data(raw);
  }

  @protected
  LoginEntryData dco_decode_box_autoadd_login_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_login_entry_data(raw);
  }

  @protected
  NoteEntryData dco_decode_box_autoadd_note_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_note_entry_data(raw);
  }

  @protected
  PassphraseConfig dco_decode_box_autoadd_passphrase_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_passphrase_config(raw);
  }

  @protected
  PasswordConfig dco_decode_box_autoadd_password_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_password_config(raw);
  }

  @protected
  VaultEntryData dco_decode_box_autoadd_vault_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vault_entry_data(raw);
  }

  @protected
  CardEntryData dco_decode_card_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 20)
      throw Exception('unexpected arr length: expect 20 but see ${arr.length}');
    return CardEntryData(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      updatedAt: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
      cardName: dco_decode_opt_String(arr[6]),
      status: dco_decode_String(arr[7]),
      cardholderName: dco_decode_String(arr[8]),
      cardNumber: dco_decode_String(arr[9]),
      expiry: dco_decode_String(arr[10]),
      cvv: dco_decode_String(arr[11]),
      creditLimit: dco_decode_opt_String(arr[12]),
      cardAccountNumber: dco_decode_opt_String(arr[13]),
      paymentNetwork: dco_decode_opt_String(arr[14]),
      pin: dco_decode_opt_String(arr[15]),
      bankName: dco_decode_opt_String(arr[16]),
      transactionPassword: dco_decode_opt_String(arr[17]),
      notes: dco_decode_opt_String(arr[18]),
      customFields: dco_decode_list_custom_field_data(arr[19]),
    );
  }

  @protected
  CsvImportConfigData dco_decode_csv_import_config_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CsvImportConfigData(
      titleCol: dco_decode_opt_String(arr[0]),
      urlCol: dco_decode_opt_String(arr[1]),
      usernameCol: dco_decode_opt_String(arr[2]),
      passwordCol: dco_decode_opt_String(arr[3]),
      notesCol: dco_decode_opt_String(arr[4]),
      favouriteCol: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  CsvPreviewData dco_decode_csv_preview_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CsvPreviewData(
      headers: dco_decode_list_String(arr[0]),
      rows: dco_decode_list_list_String(arr[1]),
    );
  }

  @protected
  CustomEntryData dco_decode_custom_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return CustomEntryData(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      updatedAt: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
      title: dco_decode_String(arr[6]),
      fields: dco_decode_list_custom_field_data(arr[7]),
    );
  }

  @protected
  CustomFieldData dco_decode_custom_field_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CustomFieldData(
      label: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
      hidden: dco_decode_bool(arr[2]),
    );
  }

  @protected
  EntropyResult dco_decode_entropy_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EntropyResult(
      bits: dco_decode_f_64(arr[0]),
      tier: dco_decode_strength_tier(arr[1]),
    );
  }

  @protected
  EntrySummaryData dco_decode_entry_summary_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EntrySummaryData(
      id: dco_decode_String(arr[0]),
      entryType: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileEntryData dco_decode_file_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return FileEntryData(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      updatedAt: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
      filename: dco_decode_String(arr[6]),
      data: dco_decode_list_prim_u_8_strict(arr[7]),
      notes: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IdentityEntryData dco_decode_identity_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return IdentityEntryData(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      updatedAt: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
      firstName: dco_decode_String(arr[6]),
      lastName: dco_decode_String(arr[7]),
      email: dco_decode_String(arr[8]),
      phone: dco_decode_opt_String(arr[9]),
      address: dco_decode_opt_String(arr[10]),
      customFields: dco_decode_list_custom_field_data(arr[11]),
    );
  }

  @protected
  Language dco_decode_language(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Language.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CustomFieldData> dco_decode_list_custom_field_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_custom_field_data).toList();
  }

  @protected
  List<EntrySummaryData> dco_decode_list_entry_summary_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry_summary_data).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LoginEntryData dco_decode_login_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return LoginEntryData(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      updatedAt: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
      title: dco_decode_String(arr[6]),
      url: dco_decode_String(arr[7]),
      username: dco_decode_String(arr[8]),
      password: dco_decode_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
      customFields: dco_decode_list_custom_field_data(arr[11]),
    );
  }

  @protected
  NoteEntryData dco_decode_note_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NoteEntryData(
      id: dco_decode_String(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      updatedAt: dco_decode_String(arr[2]),
      folder: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favourite: dco_decode_bool(arr[5]),
      title: dco_decode_String(arr[6]),
      content: dco_decode_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PassphraseConfig dco_decode_passphrase_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PassphraseConfig(
      wordCount: dco_decode_u_32(arr[0]),
      separator: dco_decode_String(arr[1]),
      capitalise: dco_decode_bool(arr[2]),
      appendNumber: dco_decode_bool(arr[3]),
      language: dco_decode_language(arr[4]),
    );
  }

  @protected
  PasswordConfig dco_decode_password_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PasswordConfig(
      length: dco_decode_u_32(arr[0]),
      useUppercase: dco_decode_bool(arr[1]),
      useLowercase: dco_decode_bool(arr[2]),
      useDigits: dco_decode_bool(arr[3]),
      useSymbols: dco_decode_bool(arr[4]),
      excludeAmbiguous: dco_decode_bool(arr[5]),
    );
  }

  @protected
  StrengthTier dco_decode_strength_tier(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StrengthTier.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultEntryData dco_decode_vault_entry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VaultEntryData_Login(
          dco_decode_box_autoadd_login_entry_data(raw[1]),
        );
      case 1:
        return VaultEntryData_Note(
          dco_decode_box_autoadd_note_entry_data(raw[1]),
        );
      case 2:
        return VaultEntryData_Identity(
          dco_decode_box_autoadd_identity_entry_data(raw[1]),
        );
      case 3:
        return VaultEntryData_Card(
          dco_decode_box_autoadd_card_entry_data(raw[1]),
        );
      case 4:
        return VaultEntryData_File(
          dco_decode_box_autoadd_file_entry_data(raw[1]),
        );
      case 5:
        return VaultEntryData_Custom(
          dco_decode_box_autoadd_custom_entry_data(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CardEntryData sse_decode_box_autoadd_card_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_card_entry_data(deserializer));
  }

  @protected
  CsvImportConfigData sse_decode_box_autoadd_csv_import_config_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_csv_import_config_data(deserializer));
  }

  @protected
  CustomEntryData sse_decode_box_autoadd_custom_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_custom_entry_data(deserializer));
  }

  @protected
  FileEntryData sse_decode_box_autoadd_file_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_file_entry_data(deserializer));
  }

  @protected
  IdentityEntryData sse_decode_box_autoadd_identity_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_identity_entry_data(deserializer));
  }

  @protected
  LoginEntryData sse_decode_box_autoadd_login_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_login_entry_data(deserializer));
  }

  @protected
  NoteEntryData sse_decode_box_autoadd_note_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_note_entry_data(deserializer));
  }

  @protected
  PassphraseConfig sse_decode_box_autoadd_passphrase_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_passphrase_config(deserializer));
  }

  @protected
  PasswordConfig sse_decode_box_autoadd_password_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_password_config(deserializer));
  }

  @protected
  VaultEntryData sse_decode_box_autoadd_vault_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vault_entry_data(deserializer));
  }

  @protected
  CardEntryData sse_decode_card_entry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    var var_cardName = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_cardholderName = sse_decode_String(deserializer);
    var var_cardNumber = sse_decode_String(deserializer);
    var var_expiry = sse_decode_String(deserializer);
    var var_cvv = sse_decode_String(deserializer);
    var var_creditLimit = sse_decode_opt_String(deserializer);
    var var_cardAccountNumber = sse_decode_opt_String(deserializer);
    var var_paymentNetwork = sse_decode_opt_String(deserializer);
    var var_pin = sse_decode_opt_String(deserializer);
    var var_bankName = sse_decode_opt_String(deserializer);
    var var_transactionPassword = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_customFields = sse_decode_list_custom_field_data(deserializer);
    return CardEntryData(
      id: var_id,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
      cardName: var_cardName,
      status: var_status,
      cardholderName: var_cardholderName,
      cardNumber: var_cardNumber,
      expiry: var_expiry,
      cvv: var_cvv,
      creditLimit: var_creditLimit,
      cardAccountNumber: var_cardAccountNumber,
      paymentNetwork: var_paymentNetwork,
      pin: var_pin,
      bankName: var_bankName,
      transactionPassword: var_transactionPassword,
      notes: var_notes,
      customFields: var_customFields,
    );
  }

  @protected
  CsvImportConfigData sse_decode_csv_import_config_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_titleCol = sse_decode_opt_String(deserializer);
    var var_urlCol = sse_decode_opt_String(deserializer);
    var var_usernameCol = sse_decode_opt_String(deserializer);
    var var_passwordCol = sse_decode_opt_String(deserializer);
    var var_notesCol = sse_decode_opt_String(deserializer);
    var var_favouriteCol = sse_decode_opt_String(deserializer);
    return CsvImportConfigData(
      titleCol: var_titleCol,
      urlCol: var_urlCol,
      usernameCol: var_usernameCol,
      passwordCol: var_passwordCol,
      notesCol: var_notesCol,
      favouriteCol: var_favouriteCol,
    );
  }

  @protected
  CsvPreviewData sse_decode_csv_preview_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_headers = sse_decode_list_String(deserializer);
    var var_rows = sse_decode_list_list_String(deserializer);
    return CsvPreviewData(headers: var_headers, rows: var_rows);
  }

  @protected
  CustomEntryData sse_decode_custom_entry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_fields = sse_decode_list_custom_field_data(deserializer);
    return CustomEntryData(
      id: var_id,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
      title: var_title,
      fields: var_fields,
    );
  }

  @protected
  CustomFieldData sse_decode_custom_field_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_hidden = sse_decode_bool(deserializer);
    return CustomFieldData(
      label: var_label,
      value: var_value,
      hidden: var_hidden,
    );
  }

  @protected
  EntropyResult sse_decode_entropy_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bits = sse_decode_f_64(deserializer);
    var var_tier = sse_decode_strength_tier(deserializer);
    return EntropyResult(bits: var_bits, tier: var_tier);
  }

  @protected
  EntrySummaryData sse_decode_entry_summary_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_entryType = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    return EntrySummaryData(
      id: var_id,
      entryType: var_entryType,
      title: var_title,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileEntryData sse_decode_file_entry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    var var_filename = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return FileEntryData(
      id: var_id,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
      filename: var_filename,
      data: var_data,
      notes: var_notes,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IdentityEntryData sse_decode_identity_entry_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    var var_firstName = sse_decode_String(deserializer);
    var var_lastName = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_phone = sse_decode_opt_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_customFields = sse_decode_list_custom_field_data(deserializer);
    return IdentityEntryData(
      id: var_id,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
      firstName: var_firstName,
      lastName: var_lastName,
      email: var_email,
      phone: var_phone,
      address: var_address,
      customFields: var_customFields,
    );
  }

  @protected
  Language sse_decode_language(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Language.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CustomFieldData> sse_decode_list_custom_field_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CustomFieldData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_custom_field_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntrySummaryData> sse_decode_list_entry_summary_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntrySummaryData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry_summary_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LoginEntryData sse_decode_login_entry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_customFields = sse_decode_list_custom_field_data(deserializer);
    return LoginEntryData(
      id: var_id,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
      title: var_title,
      url: var_url,
      username: var_username,
      password: var_password,
      notes: var_notes,
      customFields: var_customFields,
    );
  }

  @protected
  NoteEntryData sse_decode_note_entry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favourite = sse_decode_bool(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return NoteEntryData(
      id: var_id,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      folder: var_folder,
      tags: var_tags,
      favourite: var_favourite,
      title: var_title,
      content: var_content,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PassphraseConfig sse_decode_passphrase_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wordCount = sse_decode_u_32(deserializer);
    var var_separator = sse_decode_String(deserializer);
    var var_capitalise = sse_decode_bool(deserializer);
    var var_appendNumber = sse_decode_bool(deserializer);
    var var_language = sse_decode_language(deserializer);
    return PassphraseConfig(
      wordCount: var_wordCount,
      separator: var_separator,
      capitalise: var_capitalise,
      appendNumber: var_appendNumber,
      language: var_language,
    );
  }

  @protected
  PasswordConfig sse_decode_password_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_length = sse_decode_u_32(deserializer);
    var var_useUppercase = sse_decode_bool(deserializer);
    var var_useLowercase = sse_decode_bool(deserializer);
    var var_useDigits = sse_decode_bool(deserializer);
    var var_useSymbols = sse_decode_bool(deserializer);
    var var_excludeAmbiguous = sse_decode_bool(deserializer);
    return PasswordConfig(
      length: var_length,
      useUppercase: var_useUppercase,
      useLowercase: var_useLowercase,
      useDigits: var_useDigits,
      useSymbols: var_useSymbols,
      excludeAmbiguous: var_excludeAmbiguous,
    );
  }

  @protected
  StrengthTier sse_decode_strength_tier(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StrengthTier.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VaultEntryData sse_decode_vault_entry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_login_entry_data(deserializer);
        return VaultEntryData_Login(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_note_entry_data(deserializer);
        return VaultEntryData_Note(var_field0);
      case 2:
        var var_field0 = sse_decode_box_autoadd_identity_entry_data(
          deserializer,
        );
        return VaultEntryData_Identity(var_field0);
      case 3:
        var var_field0 = sse_decode_box_autoadd_card_entry_data(deserializer);
        return VaultEntryData_Card(var_field0);
      case 4:
        var var_field0 = sse_decode_box_autoadd_file_entry_data(deserializer);
        return VaultEntryData_File(var_field0);
      case 5:
        var var_field0 = sse_decode_box_autoadd_custom_entry_data(deserializer);
        return VaultEntryData_Custom(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_card_entry_data(
    CardEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_card_entry_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_csv_import_config_data(
    CsvImportConfigData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_csv_import_config_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_custom_entry_data(
    CustomEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_custom_entry_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_file_entry_data(
    FileEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_file_entry_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_identity_entry_data(
    IdentityEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_identity_entry_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_login_entry_data(
    LoginEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_login_entry_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_note_entry_data(
    NoteEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_entry_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_passphrase_config(
    PassphraseConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_passphrase_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_password_config(
    PasswordConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_password_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vault_entry_data(
    VaultEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_entry_data(self, serializer);
  }

  @protected
  void sse_encode_card_entry_data(
    CardEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
    sse_encode_opt_String(self.cardName, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.cardholderName, serializer);
    sse_encode_String(self.cardNumber, serializer);
    sse_encode_String(self.expiry, serializer);
    sse_encode_String(self.cvv, serializer);
    sse_encode_opt_String(self.creditLimit, serializer);
    sse_encode_opt_String(self.cardAccountNumber, serializer);
    sse_encode_opt_String(self.paymentNetwork, serializer);
    sse_encode_opt_String(self.pin, serializer);
    sse_encode_opt_String(self.bankName, serializer);
    sse_encode_opt_String(self.transactionPassword, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_list_custom_field_data(self.customFields, serializer);
  }

  @protected
  void sse_encode_csv_import_config_data(
    CsvImportConfigData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.titleCol, serializer);
    sse_encode_opt_String(self.urlCol, serializer);
    sse_encode_opt_String(self.usernameCol, serializer);
    sse_encode_opt_String(self.passwordCol, serializer);
    sse_encode_opt_String(self.notesCol, serializer);
    sse_encode_opt_String(self.favouriteCol, serializer);
  }

  @protected
  void sse_encode_csv_preview_data(
    CsvPreviewData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.headers, serializer);
    sse_encode_list_list_String(self.rows, serializer);
  }

  @protected
  void sse_encode_custom_entry_data(
    CustomEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_custom_field_data(self.fields, serializer);
  }

  @protected
  void sse_encode_custom_field_data(
    CustomFieldData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_bool(self.hidden, serializer);
  }

  @protected
  void sse_encode_entropy_result(EntropyResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.bits, serializer);
    sse_encode_strength_tier(self.tier, serializer);
  }

  @protected
  void sse_encode_entry_summary_data(
    EntrySummaryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.entryType, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_entry_data(
    FileEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_identity_entry_data(
    IdentityEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
    sse_encode_String(self.firstName, serializer);
    sse_encode_String(self.lastName, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_opt_String(self.phone, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_list_custom_field_data(self.customFields, serializer);
  }

  @protected
  void sse_encode_language(Language self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_custom_field_data(
    List<CustomFieldData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_custom_field_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry_summary_data(
    List<EntrySummaryData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry_summary_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_login_entry_data(
    LoginEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_list_custom_field_data(self.customFields, serializer);
  }

  @protected
  void sse_encode_note_entry_data(
    NoteEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favourite, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_passphrase_config(
    PassphraseConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.wordCount, serializer);
    sse_encode_String(self.separator, serializer);
    sse_encode_bool(self.capitalise, serializer);
    sse_encode_bool(self.appendNumber, serializer);
    sse_encode_language(self.language, serializer);
  }

  @protected
  void sse_encode_password_config(
    PasswordConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.length, serializer);
    sse_encode_bool(self.useUppercase, serializer);
    sse_encode_bool(self.useLowercase, serializer);
    sse_encode_bool(self.useDigits, serializer);
    sse_encode_bool(self.useSymbols, serializer);
    sse_encode_bool(self.excludeAmbiguous, serializer);
  }

  @protected
  void sse_encode_strength_tier(StrengthTier self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault_entry_data(
    VaultEntryData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VaultEntryData_Login(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_login_entry_data(field0, serializer);
      case VaultEntryData_Note(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_note_entry_data(field0, serializer);
      case VaultEntryData_Identity(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_identity_entry_data(field0, serializer);
      case VaultEntryData_Card(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_card_entry_data(field0, serializer);
      case VaultEntryData_File(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_file_entry_data(field0, serializer);
      case VaultEntryData_Custom(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_box_autoadd_custom_entry_data(field0, serializer);
    }
  }
}
