// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool_size`, `tier_for`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Estimate the entropy of a user-typed password.
///
/// Detects which character classes are present in `password`, builds a pool
/// size from those classes, then applies:
///
///     entropy = length × log₂(pool_size)
///
/// Returns `EntropyResult { bits: 0.0, tier: Terrible }` for an empty string.
EntropyResult estimateEntropy({required String password}) =>
    RustLib.instance.api.crateApiEntropyEstimateEntropy(password: password);

/// The result of an entropy estimate.
class EntropyResult {
  /// Estimated entropy in bits. This is a lower-bound estimate based on
  /// detected character classes. Label it "estimated entropy" in the UI.
  final double bits;

  /// Coarse strength tier derived from `bits`.
  final StrengthTier tier;

  const EntropyResult({required this.bits, required this.tier});

  @override
  int get hashCode => bits.hashCode ^ tier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntropyResult &&
          runtimeType == other.runtimeType &&
          bits == other.bits &&
          tier == other.tier;
}

/// A coarse strength label for a password, derived from its estimated entropy.
///
/// Tier boundaries (in bits), anchored to published references:
///
///  <  28 bits → Terrible
///  <  36 bits → Weak
///  <  52 bits → Fair     (NIST 8-char minimum sits around 52 bits)
///  <  80 bits → Strong
///  < 128 bits → VeryStrong
///  ≥ 128 bits → Centuries (128-bit threshold = infeasible brute-force per NIST)
///
/// Display strings for these variants are intentionally kept in Flutter,
/// following the same pattern as the `Language` enum — Rust owns the
/// classification logic, Flutter owns the UI text.
enum StrengthTier { terrible, weak, fair, strong, veryStrong, centuries }
