// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Enumerate FIDO2 HID devices and return their paths (e.g. `/dev/hidraw5`).
///
/// Returns an empty list when no FIDO2 devices are present — not an error.
/// Sync — fast device scan, no I/O.
List<String> fidoListDevices() =>
    RustLib.instance.api.crateApiFidoBridgeFidoListDevices();

/// Register a new FIDO2 credential on the YubiKey at `device_path`.
///
/// Triggers one YubiKey tap. Returns credential ID and a fresh random
/// 32-byte salt — both must be stored in the vault header.
/// Async — blocks until the user taps the key.
Future<FidoCredentialData> fidoRegister({
  required String devicePath,
  required String pin,
}) => RustLib.instance.api.crateApiFidoBridgeFidoRegister(
  devicePath: devicePath,
  pin: pin,
);

/// Obtain the 32-byte hmac-secret output from the YubiKey.
///
/// `credential_id` and `salt` come from `FidoCredentialData` (stored in the
/// vault header). Triggers one YubiKey tap.
/// Async — blocks until the user taps the key.
Future<Uint8List> fidoGetHmacSecret({
  required String devicePath,
  required List<int> credentialId,
  required List<int> salt,
  required String pin,
}) => RustLib.instance.api.crateApiFidoBridgeFidoGetHmacSecret(
  devicePath: devicePath,
  credentialId: credentialId,
  salt: salt,
  pin: pin,
);

/// Credential record returned by `fido_register`.
class FidoCredentialData {
  final Uint8List credentialId;
  final Uint8List salt;

  const FidoCredentialData({required this.credentialId, required this.salt});

  @override
  int get hashCode => credentialId.hashCode ^ salt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FidoCredentialData &&
          runtimeType == other.runtimeType &&
          credentialId == other.credentialId &&
          salt == other.salt;
}
