// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sniff the headers and first 3 rows of a CSV string.
///
/// Sync — no I/O, pure string parsing.
CsvPreviewData sniffCsvFile({required String input}) =>
    RustLib.instance.api.crateApiImportSniffCsvFile(input: input);

/// Import all rows from a CSV string into the live session, then persist once.
///
/// The vault must already be unlocked — returns `Err` if no session is active.
/// Async — triggers a single vault save (Argon2id + encryption) at the end.
Future<BigInt> importFromCsv({
  required String input,
  required CsvImportConfigData config,
}) => RustLib.instance.api.crateApiImportImportFromCsv(
  input: input,
  config: config,
);

/// Column mapping config passed in by Flutter after the user maps columns.
class CsvImportConfigData {
  final String? titleCol;
  final String? urlCol;
  final String? usernameCol;
  final String? passwordCol;
  final String? notesCol;
  final String? favouriteCol;

  const CsvImportConfigData({
    this.titleCol,
    this.urlCol,
    this.usernameCol,
    this.passwordCol,
    this.notesCol,
    this.favouriteCol,
  });

  @override
  int get hashCode =>
      titleCol.hashCode ^
      urlCol.hashCode ^
      usernameCol.hashCode ^
      passwordCol.hashCode ^
      notesCol.hashCode ^
      favouriteCol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvImportConfigData &&
          runtimeType == other.runtimeType &&
          titleCol == other.titleCol &&
          urlCol == other.urlCol &&
          usernameCol == other.usernameCol &&
          passwordCol == other.passwordCol &&
          notesCol == other.notesCol &&
          favouriteCol == other.favouriteCol;
}

/// Preview of a CSV file — headers and up to 3 sample rows.
/// Returned by [`sniff_csv_file`] for Flutter's column-mapping UI.
class CsvPreviewData {
  final List<String> headers;
  final List<List<String>> rows;

  const CsvPreviewData({required this.headers, required this.rows});

  @override
  int get hashCode => headers.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvPreviewData &&
          runtimeType == other.runtimeType &&
          headers == other.headers &&
          rows == other.rows;
}
