// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `entry_id_and_title`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`

/// Sniff the headers and first 3 rows of a CSV string.
///
/// Sync — no I/O, pure string parsing.
CsvPreviewData sniffCsvFile({required String input}) =>
    RustLib.instance.api.crateApiImportSniffCsvFile(input: input);

/// Import all rows from a CSV string into the live session, then persist once.
///
/// The vault must already be unlocked — returns `Err` if no session is active.
/// Async — triggers a single vault save (Argon2id + encryption) at the end.
Future<ImportResult> importFromCsv({
  required String input,
  required CsvImportConfigData config,
}) => RustLib.instance.api.crateApiImportImportFromCsv(
  input: input,
  config: config,
);

/// Import all entries from a Bitwarden unencrypted JSON export into the
/// live session, then persist once.
///
/// `data` is the raw bytes of the Bitwarden `.json` export file.
/// The vault must already be unlocked — returns `Err` if no session is active.
///
/// Entries that fail domain validation are collected into `ImportResult.failures`
/// rather than aborting the whole import.
///
/// Async — triggers a single vault save (Argon2id + encryption) at the end.
Future<ImportResult> importFromBitwarden({required List<int> data}) =>
    RustLib.instance.api.crateApiImportImportFromBitwarden(data: data);

/// Import all entries from an Enpass JSON export into the live session,
/// then persist once.
///
/// `data` is the raw bytes of the Enpass `.json` export file.
/// The vault must already be unlocked — returns `Err` if no session is active.
///
/// Entries that fail domain validation are collected into `ImportResult.failures`
/// rather than aborting the whole import.
///
/// Async — triggers a single vault save (Argon2id + encryption) at the end.
Future<ImportResult> importFromEnpass({required List<int> data}) =>
    RustLib.instance.api.crateApiImportImportFromEnpass(data: data);

/// Import entries from a `.gabbro` vault file into the live session.
///
/// Decrypts the source vault at `path` using `passphrase`, then applies
/// UUID-based deduplication: entries whose UUID already exists in the session
/// are skipped; new entries are added. A single vault save is performed at
/// the end.
///
/// The vault must already be unlocked — returns `Err` if no session is active.
/// Async — triggers a single vault save (Argon2id + encryption) at the end.
Future<GabbroImportResult> importFromGabbro({
  required String path,
  required List<int> passphrase,
}) => RustLib.instance.api.crateApiImportImportFromGabbro(
  path: path,
  passphrase: passphrase,
);

/// Column mapping config passed in by Flutter after the user maps columns.
class CsvImportConfigData {
  final String? titleCol;
  final String? urlCol;
  final String? usernameCol;
  final String? passwordCol;
  final String? notesCol;
  final String? favouriteCol;

  const CsvImportConfigData({
    this.titleCol,
    this.urlCol,
    this.usernameCol,
    this.passwordCol,
    this.notesCol,
    this.favouriteCol,
  });

  @override
  int get hashCode =>
      titleCol.hashCode ^
      urlCol.hashCode ^
      usernameCol.hashCode ^
      passwordCol.hashCode ^
      notesCol.hashCode ^
      favouriteCol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvImportConfigData &&
          runtimeType == other.runtimeType &&
          titleCol == other.titleCol &&
          urlCol == other.urlCol &&
          usernameCol == other.usernameCol &&
          passwordCol == other.passwordCol &&
          notesCol == other.notesCol &&
          favouriteCol == other.favouriteCol;
}

/// Preview of a CSV file — headers and up to 3 sample rows.
/// Returned by [`sniff_csv_file`] for Flutter's column-mapping UI.
class CsvPreviewData {
  final List<String> headers;
  final List<List<String>> rows;

  const CsvPreviewData({required this.headers, required this.rows});

  @override
  int get hashCode => headers.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvPreviewData &&
          runtimeType == other.runtimeType &&
          headers == other.headers &&
          rows == other.rows;
}

/// Returned by [`import_from_gabbro`].
class GabbroImportResult {
  /// Number of entries added to the session.
  final BigInt imported;

  /// Entries that were skipped (UUID already present in the session).
  final List<SkippedEntryData> skipped;

  const GabbroImportResult({required this.imported, required this.skipped});

  @override
  int get hashCode => imported.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GabbroImportResult &&
          runtimeType == other.runtimeType &&
          imported == other.imported &&
          skipped == other.skipped;
}

/// A single entry that failed domain validation during import.
///
/// Carries enough information for Flutter to show the user what was rejected
/// and why, and to pre-populate `CreateEntryScreen` for manual correction.
class ImportFailureData {
  /// Display title of the failed item (from the source file).
  final String title;

  /// Source category string (e.g. `"creditcard"`, `"login"`).
  final String category;

  /// Human-readable rejection reason (e.g. `"card number must be 12–19 digits"`).
  final String reason;

  /// Raw field values from the source file, as `(key, value)` pairs.
  /// Keys use Gabbro's canonical names where mappable
  /// (`"card_number"`, `"username"`, `"password"`, `"url"`, `"notes"`),
  /// falling back to the source label for unmapped fields.
  final List<(String, String)> rawFields;

  const ImportFailureData({
    required this.title,
    required this.category,
    required this.reason,
    required this.rawFields,
  });

  @override
  int get hashCode =>
      title.hashCode ^ category.hashCode ^ reason.hashCode ^ rawFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportFailureData &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          category == other.category &&
          reason == other.reason &&
          rawFields == other.rawFields;
}

/// Returned by all three import bridge functions.
class ImportResult {
  /// Number of entries successfully imported into the vault.
  final BigInt imported;

  /// Entries that failed domain validation and were not imported.
  final List<ImportFailureData> failures;

  /// Entries skipped because their UUID already exists in the vault.
  final List<SkippedEntryData> skipped;

  const ImportResult({
    required this.imported,
    required this.failures,
    required this.skipped,
  });

  @override
  int get hashCode => imported.hashCode ^ failures.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportResult &&
          runtimeType == other.runtimeType &&
          imported == other.imported &&
          failures == other.failures &&
          skipped == other.skipped;
}

/// A single entry skipped during Gabbro → Gabbro import.
class SkippedEntryData {
  /// Display title of the skipped entry.
  final String title;

  /// Human-readable reason for skipping.
  final String reason;

  const SkippedEntryData({required this.title, required this.reason});

  @override
  int get hashCode => title.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkippedEntryData &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          reason == other.reason;
}
