// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `wordlist_for`

/// Generate a passphrase from the given config.
/// Returns Err if word_count is 0 or the wordlist is empty.
Future<String> generatePassphrase({required PassphraseConfig config}) => RustLib
    .instance
    .api
    .crateApiPassphraseGeneratorGeneratePassphrase(config: config);

/// Calculate entropy in bits for a passphrase.
/// Uses the actual wordlist size for the given language.
Future<double> passphraseEntropyBits({
  required int wordCount,
  required Language language,
}) => RustLib.instance.api.crateApiPassphraseGeneratorPassphraseEntropyBits(
  wordCount: wordCount,
  language: language,
);

class PassphraseConfig {
  final int wordCount;
  final String separator;
  final bool capitalise;
  final bool appendNumber;
  final Language language;

  const PassphraseConfig({
    required this.wordCount,
    required this.separator,
    required this.capitalise,
    required this.appendNumber,
    required this.language,
  });

  @override
  int get hashCode =>
      wordCount.hashCode ^
      separator.hashCode ^
      capitalise.hashCode ^
      appendNumber.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassphraseConfig &&
          runtimeType == other.runtimeType &&
          wordCount == other.wordCount &&
          separator == other.separator &&
          capitalise == other.capitalise &&
          appendNumber == other.appendNumber &&
          language == other.language;
}
