// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `b64url_encode`, `b64url`, `placeholder_client_data`, `spki_from_cose`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawCreationOptions`, `RawDescriptor`, `RawParam`, `RawRequestOptions`, `RawRp`, `RawUser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Parse a W3C `PublicKeyCredentialCreationOptions` JSON string.
///
/// Strict on purpose: a missing rp.id or a parameter list without ES256 is a
/// refusal here, so the user never stores a credential that can't sign for the
/// site that requested it.
Future<CreationRequest> parseCreationRequest({required String json}) =>
    RustLib.instance.api.crateApiPasskeyBridgeParseCreationRequest(json: json);

/// Register a new passkey from a relying party's creation request: mint the
/// key pair, store the credential as a vault entry (persisted like any entry),
/// and return the public parts for the response. Fails when the vault is
/// locked — the caller shows the unlock flow and retries.
Future<RegistrationParts> registerPasskey({required String requestJson}) =>
    RustLib.instance.api.crateApiPasskeyBridgeRegisterPasskey(
      requestJson: requestJson,
    );

/// Core registration shared by the Android (W3C JSON) and Linux (CTAP2 CBOR)
/// paths: mint the key, store the vault entry, return the public parts.
Future<RegistrationParts> registerPasskeyParts({
  required String rpId,
  required String userName,
  required String userDisplayName,
  required List<int> userHandle,
}) => RustLib.instance.api.crateApiPasskeyBridgeRegisterPasskeyParts(
  rpId: rpId,
  userName: userName,
  userDisplayName: userDisplayName,
  userHandle: userHandle,
);

/// Parse a W3C `PublicKeyCredentialRequestOptions` JSON string. A missing rpId
/// is refused: without it there is nothing safe to match credentials against.
Future<AssertionRequest> parseAssertionRequest({required String json}) =>
    RustLib.instance.api.crateApiPasskeyBridgeParseAssertionRequest(json: json);

/// The vault's credentials answering a sign-in request: exact rp_id match only
/// (a passkey for example.com must never answer a lookalike), narrowed by the
/// relying party's allow-list when it names specific credentials.
Future<List<PasskeyMatchData>> passkeysForRequest({
  required String requestJson,
}) => RustLib.instance.api.crateApiPasskeyBridgePasskeysForRequest(
  requestJson: requestJson,
);

/// Sign a relying party's challenge with the chosen credential. The private
/// key is read from the session and never leaves this function.
Future<AssertionParts> signPasskeyAssertion({
  required String entryId,
  required List<int> clientDataHash,
}) => RustLib.instance.api.crateApiPasskeyBridgeSignPasskeyAssertion(
  entryId: entryId,
  clientDataHash: clientDataHash,
);

/// Register a passkey and return the complete W3C `RegistrationResponseJSON`
/// the caller sends back verbatim. `client_data_json_b64url` is included when
/// the provider built the client data itself (native-app flow); privileged
/// browsers supply their own and pass `None`.
Future<String> registrationResponseJson({
  required String requestJson,
  String? clientDataJsonB64Url,
}) => RustLib.instance.api.crateApiPasskeyBridgeRegistrationResponseJson(
  requestJson: requestJson,
  clientDataJsonB64Url: clientDataJsonB64Url,
);

/// Sign and return the complete W3C `AuthenticationResponseJSON`.
///
/// Exactly one client-data source: the provider-built clientDataJSON (native
/// apps — we hash it ourselves and include it), or the caller's pre-computed
/// hash (privileged browsers — they attach their own clientDataJSON).
Future<String> assertionResponseJson({
  required String entryId,
  String? clientDataJsonB64Url,
  String? clientDataHashB64Url,
}) => RustLib.instance.api.crateApiPasskeyBridgeAssertionResponseJson(
  entryId: entryId,
  clientDataJsonB64Url: clientDataJsonB64Url,
  clientDataHashB64Url: clientDataHashB64Url,
);

/// What Kotlin needs to assemble the sign-in response.
class AssertionParts {
  final Uint8List credentialId;
  final Uint8List authData;
  final Uint8List signatureDer;
  final Uint8List userHandle;

  const AssertionParts({
    required this.credentialId,
    required this.authData,
    required this.signatureDer,
    required this.userHandle,
  });

  @override
  int get hashCode =>
      credentialId.hashCode ^
      authData.hashCode ^
      signatureDer.hashCode ^
      userHandle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssertionParts &&
          runtimeType == other.runtimeType &&
          credentialId == other.credentialId &&
          authData == other.authData &&
          signatureDer == other.signatureDer &&
          userHandle == other.userHandle;
}

/// A parsed WebAuthn sign-in request.
class AssertionRequest {
  final String rpId;
  final Uint8List challenge;

  /// Credential ids the relying party will accept; empty = any discoverable
  /// credential for the rp.
  final List<Uint8List> allowCredentialIds;

  const AssertionRequest({
    required this.rpId,
    required this.challenge,
    required this.allowCredentialIds,
  });

  @override
  int get hashCode =>
      rpId.hashCode ^ challenge.hashCode ^ allowCredentialIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssertionRequest &&
          runtimeType == other.runtimeType &&
          rpId == other.rpId &&
          challenge == other.challenge &&
          allowCredentialIds == other.allowCredentialIds;
}

/// A parsed WebAuthn registration request — only the fields Gabbro needs to
/// mint and store a credential.
class CreationRequest {
  final String rpId;
  final Uint8List userHandle;
  final String userName;
  final String userDisplayName;
  final Uint8List challenge;

  const CreationRequest({
    required this.rpId,
    required this.userHandle,
    required this.userName,
    required this.userDisplayName,
    required this.challenge,
  });

  @override
  int get hashCode =>
      rpId.hashCode ^
      userHandle.hashCode ^
      userName.hashCode ^
      userDisplayName.hashCode ^
      challenge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreationRequest &&
          runtimeType == other.runtimeType &&
          rpId == other.rpId &&
          userHandle == other.userHandle &&
          userName == other.userName &&
          userDisplayName == other.userDisplayName &&
          challenge == other.challenge;
}

/// One selectable credential for the caller's account picker. No key material.
class PasskeyMatchData {
  final String entryId;
  final String rpId;
  final String userName;
  final String userDisplayName;
  final Uint8List credentialId;

  const PasskeyMatchData({
    required this.entryId,
    required this.rpId,
    required this.userName,
    required this.userDisplayName,
    required this.credentialId,
  });

  @override
  int get hashCode =>
      entryId.hashCode ^
      rpId.hashCode ^
      userName.hashCode ^
      userDisplayName.hashCode ^
      credentialId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasskeyMatchData &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          rpId == other.rpId &&
          userName == other.userName &&
          userDisplayName == other.userDisplayName &&
          credentialId == other.credentialId;
}

/// What Kotlin needs to assemble the registration response. Everything here is
/// public material — the private key stayed in the vault entry.
class RegistrationParts {
  final Uint8List credentialId;
  final Uint8List authData;
  final Uint8List publicKeyCose;

  const RegistrationParts({
    required this.credentialId,
    required this.authData,
    required this.publicKeyCose,
  });

  @override
  int get hashCode =>
      credentialId.hashCode ^ authData.hashCode ^ publicKeyCose.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegistrationParts &&
          runtimeType == other.runtimeType &&
          credentialId == other.credentialId &&
          authData == other.authData &&
          publicKeyCose == other.publicKeyCose;
}
