// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a random password according to the given config.
/// Returns an error string if the config produces an empty character pool.
String generatePassword({required PasswordConfig config}) => RustLib
    .instance
    .api
    .crateApiPasswordGeneratorGeneratePassword(config: config);

/// Calculate entropy in bits for a password of given length drawn from a pool of given size.
/// Formula: entropy = length × log₂(pool_size)
double entropyBits({required int poolSize, required int length}) => RustLib
    .instance
    .api
    .crateApiPasswordGeneratorEntropyBits(poolSize: poolSize, length: length);

/// Configuration for classic password generation.
class PasswordConfig {
  final int length;
  final bool useUppercase;
  final bool useLowercase;
  final bool useDigits;
  final bool useSymbols;
  final bool excludeAmbiguous;

  const PasswordConfig({
    required this.length,
    required this.useUppercase,
    required this.useLowercase,
    required this.useDigits,
    required this.useSymbols,
    required this.excludeAmbiguous,
  });

  @override
  int get hashCode =>
      length.hashCode ^
      useUppercase.hashCode ^
      useLowercase.hashCode ^
      useDigits.hashCode ^
      useSymbols.hashCode ^
      excludeAmbiguous.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordConfig &&
          runtimeType == other.runtimeType &&
          length == other.length &&
          useUppercase == other.useUppercase &&
          useLowercase == other.useLowercase &&
          useDigits == other.useDigits &&
          useSymbols == other.useSymbols &&
          excludeAmbiguous == other.excludeAmbiguous;
}
