// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Describe one reassembled CTAP2 request (command byte + CBOR): no crypto,
/// no signing.
Future<PasskeyPlan> passkeyPlan({required List<int> payload}) => RustLib
    .instance
    .api
    .crateApiPasskeyDaemonBridgePasskeyPlan(payload: payload);

/// Perform a user-approved request; `account_index` selects among the accounts
/// `passkey_plan` listed (ignored for a create).
Future<Uint8List> passkeyPerform({
  required List<int> payload,
  required BigInt accountIndex,
}) => RustLib.instance.api.crateApiPasskeyDaemonBridgePasskeyPerform(
  payload: payload,
  accountIndex: accountIndex,
);

/// The response to frame back when the user cancels at the consent dialog.
Future<Uint8List> passkeyDenied() =>
    RustLib.instance.api.crateApiPasskeyDaemonBridgePasskeyDenied();

/// Start the Linux passkey daemon: create the uhid device and stream each
/// complete CTAP2 request (command byte + CBOR) to Dart. Rust keeps the
/// request alive with KEEPALIVE until `passkey_daemon_respond`.
Stream<Uint8List> passkeyDaemonStart() =>
    RustLib.instance.api.crateApiPasskeyDaemonBridgePasskeyDaemonStart();

/// Hand a finished CTAP2 response (or the denied bytes) back to the daemon.
Future<void> passkeyDaemonRespond({required List<int> response}) => RustLib
    .instance
    .api
    .crateApiPasskeyDaemonBridgePasskeyDaemonRespond(response: response);

/// Stop the daemon and unplug the virtual device.
Future<void> passkeyDaemonStop() =>
    RustLib.instance.api.crateApiPasskeyDaemonBridgePasskeyDaemonStop();

/// What the daemon should do with one CTAP2 request. When `immediate_response`
/// is set the daemon frames those bytes straight back (getInfo, locked vault,
/// no match, malformed); otherwise it shows the consent dialog for `rp_id`,
/// offering `accounts`, then calls `passkey_perform` with the chosen index.
class PasskeyPlan {
  final Uint8List? immediateResponse;
  final bool isCreate;
  final String rpId;
  final List<String> accounts;

  const PasskeyPlan({
    this.immediateResponse,
    required this.isCreate,
    required this.rpId,
    required this.accounts,
  });

  @override
  int get hashCode =>
      immediateResponse.hashCode ^
      isCreate.hashCode ^
      rpId.hashCode ^
      accounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasskeyPlan &&
          runtimeType == other.runtimeType &&
          immediateResponse == other.immediateResponse &&
          isCreate == other.isCreate &&
          rpId == other.rpId &&
          accounts == other.accounts;
}
