// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Raise (`true`) or lower (`false`) the process `PR_SET_DUMPABLE` flag.
///
/// The Linux picker layer raises it only while a native file dialog is open so
/// `xdg-desktop-portal` can read `/proc/<pid>` to service the request, then
/// lowers it again. No-op on non-Linux targets. See
/// `crate::hardening::set_process_dumpable`.
Future<void> setProcessDumpable({required bool dumpable}) =>
    RustLib.instance.api.crateApiSimpleSetProcessDumpable(dumpable: dumpable);
