// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Passphrase / password generator language.
///
/// Each variant maps to an embedded wordlist (passphrase mode) and to a
/// script-specific character pool (classic mode).  `nb` covers both Bokmål
/// and Nynorsk; `pt` covers both pt-PT and pt-BR; `nl` covers Dutch and Flemish.
enum Language {
  english,
  french,
  german,
  spanish,
  italian,
  swedish,
  danish,
  norwegian,
  finnish,
  slovenian,
  polish,
  russian,
  hungarian,
  czech,
  greek,
  portuguese,
  estonian,
  slovak,
  bulgarian,
  ukrainian,
  japanese,
  korean,
  chineseSimplified,
  chineseTraditional,
  dutch,
  croatian,
  lithuanian,
  latvian,
  kazakh,
}
