// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_days_to_timestamp`, `card_entry_to_data`, `custom_entry_to_data`, `custom_field_to_data`, `days_from_ymd`, `days_to_ymd`, `entry_id`, `file_entry_to_data`, `identity_entry_to_data`, `is_expired`, `is_leap`, `login_entry_to_data`, `mask_entry`, `note_entry_to_data`, `previous_secret_to_data`, `purge_expired_history`, `write_sha256_companion`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_yubikey_to_vault`, `change_passphrase_with_keys`, `change_passphrase`, `delete_entry`, `delete_whole_vault`, `export_vault_preserving`, `export_vault`, `get_entry_by_id`, `list_entries`, `load_vault_with_key_record`, `load_vault_with_yubikey`, `load_vault`, `remove_yubikey_from_vault`, `reseal_vault_body`, `save_vault_with_keys`, `save_vault_with_yubikey`, `save_vault`, `update_entry`

/// Creates a new login entry with a generated UUID and current timestamp.
///
/// Called by Flutter when the user saves a new login. Returns a
/// `LoginEntryData` DTO — the internal `LoginEntry` never crosses the bridge.
Future<LoginEntryData> createLoginEntry({
  required String folder,
  required String title,
  required String url,
  required String username,
  required String password,
  String? notes,
  required List<CustomFieldData> customFields,
}) => RustLib.instance.api.crateApiVaultCreateLoginEntry(
  folder: folder,
  title: title,
  url: url,
  username: username,
  password: password,
  notes: notes,
  customFields: customFields,
);

/// Creates a new note entry with a generated UUID and current timestamp.
Future<NoteEntryData> createNoteEntry({
  required String folder,
  required String title,
  required String content,
  required List<CustomFieldData> customFields,
}) => RustLib.instance.api.crateApiVaultCreateNoteEntry(
  folder: folder,
  title: title,
  content: content,
  customFields: customFields,
);

/// Creates a new identity entry with a generated UUID and current timestamp.
Future<IdentityEntryData> createIdentityEntry({
  required String folder,
  required String firstName,
  required String lastName,
  required String email,
  String? phone,
  String? address,
}) => RustLib.instance.api.crateApiVaultCreateIdentityEntry(
  folder: folder,
  firstName: firstName,
  lastName: lastName,
  email: email,
  phone: phone,
  address: address,
);

/// Creates a new card entry with a generated UUID and current timestamp.
///
/// Returns an error if the card number does not contain 12-19 digits.
Future<CardEntryData> createCardEntry({
  required String folder,
  String? cardName,
  required String status,
  required String cardholderName,
  required String cardNumber,
  required String expiry,
  required String cvv,
  String? creditLimit,
  String? cardAccountNumber,
  String? paymentNetwork,
  String? pin,
  String? bankName,
  String? transactionPassword,
  String? notes,
}) => RustLib.instance.api.crateApiVaultCreateCardEntry(
  folder: folder,
  cardName: cardName,
  status: status,
  cardholderName: cardholderName,
  cardNumber: cardNumber,
  expiry: expiry,
  cvv: cvv,
  creditLimit: creditLimit,
  cardAccountNumber: cardAccountNumber,
  paymentNetwork: paymentNetwork,
  pin: pin,
  bankName: bankName,
  transactionPassword: transactionPassword,
  notes: notes,
);

/// Creates a new file entry with a generated UUID and current timestamp.
Future<FileEntryData> createFileEntry({
  required String folder,
  required String filename,
  required List<int> data,
  String? notes,
  required List<CustomFieldData> customFields,
}) => RustLib.instance.api.crateApiVaultCreateFileEntry(
  folder: folder,
  filename: filename,
  data: data,
  notes: notes,
  customFields: customFields,
);

/// Creates a new custom entry with a generated UUID and current timestamp.
Future<CustomEntryData> createCustomEntry({
  required String folder,
  required String title,
  required List<CustomFieldData> fields,
}) => RustLib.instance.api.crateApiVaultCreateCustomEntry(
  folder: folder,
  title: title,
  fields: fields,
);

/// Returns the current UTC time as an ISO 8601 string.
/// Uses std only — no chrono dependency needed at this stage.
Future<String> chronoNow() => RustLib.instance.api.crateApiVaultChronoNow();

/// A card entry as seen by Flutter.
class CardEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String? cardName;
  final String status;
  final String cardholderName;
  final String cardNumber;
  final String expiry;
  final String cvv;
  final String? creditLimit;
  final String? cardAccountNumber;
  final String? paymentNetwork;
  final String? pin;
  final String? bankName;
  final String? transactionPassword;
  final String? notes;
  final List<CustomFieldData> customFields;

  /// Previous CVV, masked by default. `None` if no history exists.
  final PreviousSecretData? previousCvv;

  /// Previous PIN, masked by default. `None` if no history exists.
  final PreviousSecretData? previousPin;

  const CardEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    this.cardName,
    required this.status,
    required this.cardholderName,
    required this.cardNumber,
    required this.expiry,
    required this.cvv,
    this.creditLimit,
    this.cardAccountNumber,
    this.paymentNetwork,
    this.pin,
    this.bankName,
    this.transactionPassword,
    this.notes,
    required this.customFields,
    this.previousCvv,
    this.previousPin,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      cardName.hashCode ^
      status.hashCode ^
      cardholderName.hashCode ^
      cardNumber.hashCode ^
      expiry.hashCode ^
      cvv.hashCode ^
      creditLimit.hashCode ^
      cardAccountNumber.hashCode ^
      paymentNetwork.hashCode ^
      pin.hashCode ^
      bankName.hashCode ^
      transactionPassword.hashCode ^
      notes.hashCode ^
      customFields.hashCode ^
      previousCvv.hashCode ^
      previousPin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          cardName == other.cardName &&
          status == other.status &&
          cardholderName == other.cardholderName &&
          cardNumber == other.cardNumber &&
          expiry == other.expiry &&
          cvv == other.cvv &&
          creditLimit == other.creditLimit &&
          cardAccountNumber == other.cardAccountNumber &&
          paymentNetwork == other.paymentNetwork &&
          pin == other.pin &&
          bankName == other.bankName &&
          transactionPassword == other.transactionPassword &&
          notes == other.notes &&
          customFields == other.customFields &&
          previousCvv == other.previousCvv &&
          previousPin == other.previousPin;
}

/// A custom entry as seen by Flutter.
class CustomEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String title;
  final List<CustomFieldData> fields;

  const CustomEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.title,
    required this.fields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      title.hashCode ^
      fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          title == other.title &&
          fields == other.fields;
}

/// A custom field as seen by Flutter.
class CustomFieldData {
  final String label;
  final String value;
  final bool hidden;

  const CustomFieldData({
    required this.label,
    required this.value,
    required this.hidden,
  });

  @override
  int get hashCode => label.hashCode ^ value.hashCode ^ hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldData &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          hidden == other.hidden;
}

/// A file entry as seen by Flutter.
class FileEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String filename;
  final Uint8List data;
  final String? notes;
  final List<CustomFieldData> customFields;

  const FileEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.filename,
    required this.data,
    this.notes,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      filename.hashCode ^
      data.hashCode ^
      notes.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          filename == other.filename &&
          data == other.data &&
          notes == other.notes &&
          customFields == other.customFields;
}

/// A folder assignment conflict discovered during vault merge.
///
/// Returned when the same entry UUID exists in both vaults assigned to different
/// folders. Flutter prompts the user to pick which folder to keep.
class FolderConflictItem {
  final String id;
  final String title;
  final String localFolder;
  final String incomingFolder;

  const FolderConflictItem({
    required this.id,
    required this.title,
    required this.localFolder,
    required this.incomingFolder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      localFolder.hashCode ^
      incomingFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderConflictItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          localFolder == other.localFolder &&
          incomingFolder == other.incomingFolder;
}

/// An identity entry as seen by Flutter.
class IdentityEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String firstName;
  final String lastName;
  final String email;
  final String? phone;
  final String? address;
  final List<CustomFieldData> customFields;

  const IdentityEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.phone,
    this.address,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          customFields == other.customFields;
}

/// A login entry as seen by Flutter.
class LoginEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;

  /// Human-readable item title (e.g. "GitHub", "Netflix").
  /// Distinct from the URL — used as the primary display label in list views.
  final String title;
  final String url;
  final String username;
  final String password;
  final String? notes;
  final List<CustomFieldData> customFields;

  /// Previous password, masked by default. `None` if no history exists.
  final PreviousSecretData? previousPassword;

  const LoginEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.title,
    required this.url,
    required this.username,
    required this.password,
    this.notes,
    required this.customFields,
    this.previousPassword,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      title.hashCode ^
      url.hashCode ^
      username.hashCode ^
      password.hashCode ^
      notes.hashCode ^
      customFields.hashCode ^
      previousPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          title == other.title &&
          url == other.url &&
          username == other.username &&
          password == other.password &&
          notes == other.notes &&
          customFields == other.customFields &&
          previousPassword == other.previousPassword;
}

/// Summary returned to Flutter after a vault merge operation.
class MergeSummary {
  /// Entries added from the incoming vault (UUIDs not present locally).
  final int added;

  /// Entries updated because the incoming version had a newer timestamp.
  final int updated;

  /// Incoming tombstones that matched local entries — awaiting user consent.
  /// Flutter shows a Delete/Keep dialog for each; no deletion occurs automatically.
  final List<PendingDeleteItem> pendingDeletes;

  /// Same-UUID entries with different folder assignments on each device.
  /// Flutter prompts the user to pick which folder to keep.
  final List<FolderConflictItem> folderConflicts;

  const MergeSummary({
    required this.added,
    required this.updated,
    required this.pendingDeletes,
    required this.folderConflicts,
  });

  @override
  int get hashCode =>
      added.hashCode ^
      updated.hashCode ^
      pendingDeletes.hashCode ^
      folderConflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergeSummary &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          updated == other.updated &&
          pendingDeletes == other.pendingDeletes &&
          folderConflicts == other.folderConflicts;
}

/// A note entry as seen by Flutter.
class NoteEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String title;
  final String content;
  final List<CustomFieldData> customFields;

  const NoteEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.title,
    required this.content,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      title.hashCode ^
      content.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          title == other.title &&
          content == other.content &&
          customFields == other.customFields;
}

/// An entry flagged for user-consent deletion during vault merge.
///
/// Returned when an incoming vault contains a tombstone that matches a local
/// entry. Flutter shows a per-entry Delete/Keep dialog before any deletion occurs.
class PendingDeleteItem {
  final String id;
  final String title;

  const PendingDeleteItem({required this.id, required this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingDeleteItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}

/// A previous sensitive value as seen by Flutter.
/// `value` is always masked at the bridge boundary — Flutter unmasks on toggle.
class PreviousSecretData {
  final String value;
  final String savedAt;
  final String? expiresAt;

  const PreviousSecretData({
    required this.value,
    required this.savedAt,
    this.expiresAt,
  });

  @override
  int get hashCode => value.hashCode ^ savedAt.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviousSecretData &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          savedAt == other.savedAt &&
          expiresAt == other.expiresAt;
}
