// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_days_to_timestamp`, `changed_field_keys`, `custom_field_to_data`, `days_from_ymd`, `days_to_ymd`, `entry_custom_fields_mut`, `entry_id`, `entry_meta_mut`, `entry_meta`, `is_expired`, `is_leap`, `item_keys`, `login_entry_to_data`, `mask_entry`, `purge_expired_history`, `remove_entry_item_by_key`, `set_entry_field_by_key`, `set_entry_scalar`, `write_sha256_companion`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_yubikey_to_vault`, `build_passphrase_only_bytes`, `change_passphrase_with_keys`, `change_passphrase`, `delete_entry`, `delete_whole_vault`, `export_vault_preserving`, `export_vault`, `list_entries`, `load_vault_with_key_record`, `load_vault_with_yubikey`, `load_vault`, `remove_yubikey_from_vault`, `reseal_vault_body`, `save_vault_with_keys`, `save_vault_with_yubikey`, `save_vault`, `sha256_line`, `update_entry`

/// Creates a new login entry with a generated UUID and current timestamp.
///
/// Called by Flutter when the user saves a new login. Returns a
/// `LoginEntryData` DTO — the internal `LoginEntry` never crosses the bridge.
Future<LoginEntryData> createLoginEntry({
  required String folder,
  required String title,
  required String url,
  required String username,
  required String password,
  String? notes,
  required List<CustomFieldData> customFields,
}) => RustLib.instance.api.crateApiVaultCreateLoginEntry(
  folder: folder,
  title: title,
  url: url,
  username: username,
  password: password,
  notes: notes,
  customFields: customFields,
);

/// Current time in milliseconds since the Unix epoch. Std-only (no date crate):
/// per-field change-times are only ever generated and compared as integers, never
/// parsed, so a real date library buys nothing here.
Future<BigInt> nowMs() => RustLib.instance.api.crateApiVaultNowMs();

/// Returns the current UTC time as an ISO 8601 string.
/// Uses std only — no chrono dependency needed at this stage.
Future<String> chronoNow() => RustLib.instance.api.crateApiVaultChronoNow();

/// An entry added from the incoming vault during sync (its UUID was not present
/// locally). Surfaced so the user can review and drop it before keeping it
/// (drop = delete the entry). `title` is the display title.
class AddedEntryItem {
  final String id;
  final String title;

  const AddedEntryItem({required this.id, required this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddedEntryItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}

/// A non-conflicting value brought over from the incoming vault during sync: the
/// other device edited this field/pair/attachment and this side did not, so the
/// incoming value wins additively. Surfaced so the user can review and drop it
/// (drop = restore `old_value`). `field` is the field key (e.g. "password",
/// "custom_fields:Tag", "attachments:ID"). For a newly added pair/attachment,
/// `old_value` is empty and `new_value` is the item's value/name. Values are
/// decrypted plaintext — mask secrets in the UI. Genuine clashes are NOT here;
/// see `field_conflicts`.
class BroughtOverItem {
  final String id;
  final String title;
  final String field;
  final String oldValue;
  final String newValue;

  const BroughtOverItem({
    required this.id,
    required this.title,
    required this.field,
    required this.oldValue,
    required this.newValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      field.hashCode ^
      oldValue.hashCode ^
      newValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BroughtOverItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          field == other.field &&
          oldValue == other.oldValue &&
          newValue == other.newValue;
}

/// A card entry as seen by Flutter.
class CardEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String? cardName;
  final String status;
  final String cardholderName;
  final String cardNumber;
  final String expiry;
  final String cvv;
  final String? creditLimit;
  final String? cardAccountNumber;
  final String? paymentNetwork;
  final String? pin;
  final String? bankName;
  final String? transactionPassword;
  final String? notes;
  final List<CustomFieldData> customFields;

  const CardEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    this.cardName,
    required this.status,
    required this.cardholderName,
    required this.cardNumber,
    required this.expiry,
    required this.cvv,
    this.creditLimit,
    this.cardAccountNumber,
    this.paymentNetwork,
    this.pin,
    this.bankName,
    this.transactionPassword,
    this.notes,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      cardName.hashCode ^
      status.hashCode ^
      cardholderName.hashCode ^
      cardNumber.hashCode ^
      expiry.hashCode ^
      cvv.hashCode ^
      creditLimit.hashCode ^
      cardAccountNumber.hashCode ^
      paymentNetwork.hashCode ^
      pin.hashCode ^
      bankName.hashCode ^
      transactionPassword.hashCode ^
      notes.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          cardName == other.cardName &&
          status == other.status &&
          cardholderName == other.cardholderName &&
          cardNumber == other.cardNumber &&
          expiry == other.expiry &&
          cvv == other.cvv &&
          creditLimit == other.creditLimit &&
          cardAccountNumber == other.cardAccountNumber &&
          paymentNetwork == other.paymentNetwork &&
          pin == other.pin &&
          bankName == other.bankName &&
          transactionPassword == other.transactionPassword &&
          notes == other.notes &&
          customFields == other.customFields;
}

/// A custom entry as seen by Flutter.
class CustomEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String title;
  final List<CustomFieldData> fields;

  const CustomEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.title,
    required this.fields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      title.hashCode ^
      fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          title == other.title &&
          fields == other.fields;
}

/// A custom field as seen by Flutter.
class CustomFieldData {
  final String label;
  final String value;
  final bool hidden;

  const CustomFieldData({
    required this.label,
    required this.value,
    required this.hidden,
  });

  @override
  int get hashCode => label.hashCode ^ value.hashCode ^ hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldData &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          hidden == other.hidden;
}

/// A true field-level clash discovered during vault merge: the same field of the
/// same entry was changed on both devices at the same instant to different values.
/// The local value is kept; Flutter prompts the user to keep mine / keep theirs.
/// `local_value` / `incoming_value` are decrypted plaintext — mask in the UI like
/// any other secret. `field` is the field key (e.g. "password", "custom_fields:PIN").
class FieldConflictItem {
  final String id;
  final String title;
  final String field;
  final String localValue;
  final String incomingValue;

  const FieldConflictItem({
    required this.id,
    required this.title,
    required this.field,
    required this.localValue,
    required this.incomingValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      field.hashCode ^
      localValue.hashCode ^
      incomingValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldConflictItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          field == other.field &&
          localValue == other.localValue &&
          incomingValue == other.incomingValue;
}

/// A file entry as seen by Flutter.
class FileEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String filename;
  final Uint8List data;
  final String? notes;
  final List<CustomFieldData> customFields;

  const FileEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.filename,
    required this.data,
    this.notes,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      filename.hashCode ^
      data.hashCode ^
      notes.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          filename == other.filename &&
          data == other.data &&
          notes == other.notes &&
          customFields == other.customFields;
}

/// A folder assignment conflict discovered during vault merge.
///
/// Returned when the same entry UUID exists in both vaults assigned to different
/// folders. Flutter prompts the user to pick which folder to keep.
class FolderConflictItem {
  final String id;
  final String title;
  final String localFolder;
  final String incomingFolder;

  const FolderConflictItem({
    required this.id,
    required this.title,
    required this.localFolder,
    required this.incomingFolder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      localFolder.hashCode ^
      incomingFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderConflictItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          localFolder == other.localFolder &&
          incomingFolder == other.incomingFolder;
}

/// A recovery-history record for Flutter: a value replaced during sync, kept so
/// the user can restore it. `value` is plaintext — Flutter masks secret fields.
class HistoryRecordData {
  final String field;
  final String value;
  final String savedAt;
  final String? expiresAt;

  const HistoryRecordData({
    required this.field,
    required this.value,
    required this.savedAt,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      field.hashCode ^ value.hashCode ^ savedAt.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryRecordData &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          value == other.value &&
          savedAt == other.savedAt &&
          expiresAt == other.expiresAt;
}

/// An identity entry as seen by Flutter.
class IdentityEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String firstName;
  final String lastName;
  final String email;
  final String? phone;
  final String? address;
  final List<CustomFieldData> customFields;

  const IdentityEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.phone,
    this.address,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      address.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          email == other.email &&
          phone == other.phone &&
          address == other.address &&
          customFields == other.customFields;
}

/// A login entry as seen by Flutter.
class LoginEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;

  /// Human-readable item title (e.g. "Example", "Sample").
  /// Distinct from the URL — used as the primary display label in list views.
  final String title;
  final String url;
  final String username;
  final String password;
  final String? notes;
  final List<CustomFieldData> customFields;

  /// Android application id for native-app autofill matching; `None` if unset.
  final String? appId;

  /// Email/identifier routed to email-typed fields; `None` if unset.
  final String? email;

  const LoginEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.title,
    required this.url,
    required this.username,
    required this.password,
    this.notes,
    required this.customFields,
    this.appId,
    this.email,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      title.hashCode ^
      url.hashCode ^
      username.hashCode ^
      password.hashCode ^
      notes.hashCode ^
      customFields.hashCode ^
      appId.hashCode ^
      email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          title == other.title &&
          url == other.url &&
          username == other.username &&
          password == other.password &&
          notes == other.notes &&
          customFields == other.customFields &&
          appId == other.appId &&
          email == other.email;
}

/// Summary returned to Flutter after a vault merge operation.
class MergeSummary {
  /// Entries added from the incoming vault (UUIDs not present locally).
  final int added;

  /// Entries updated because the incoming version had a newer timestamp.
  final int updated;

  /// Entries added from the incoming vault, listed for one-by-one review so the
  /// user can drop any (drop = delete the entry). Same count as `added`.
  final List<AddedEntryItem> addedEntries;

  /// Non-conflicting values brought over from the incoming vault, listed for
  /// review so the user can drop any (drop = restore the old value).
  final List<BroughtOverItem> broughtOver;

  /// Incoming tombstones that matched local entries — awaiting user consent.
  /// Flutter shows a Delete/Keep dialog for each; no deletion occurs automatically.
  final List<PendingDeleteItem> pendingDeletes;

  /// Same-UUID entries with different folder assignments on each device.
  /// Flutter prompts the user to pick which folder to keep.
  final List<FolderConflictItem> folderConflicts;

  /// True field-level clashes (same field, same instant, different value). The
  /// local value is kept; Flutter prompts keep mine / keep theirs.
  final List<FieldConflictItem> fieldConflicts;

  /// Items (custom pairs / attachments) the other device deleted more recently
  /// than this side edited them. The item is kept; Flutter prompts keep / delete.
  final List<PendingItemDeleteItem> pendingItemDeletes;

  const MergeSummary({
    required this.added,
    required this.updated,
    required this.addedEntries,
    required this.broughtOver,
    required this.pendingDeletes,
    required this.folderConflicts,
    required this.fieldConflicts,
    required this.pendingItemDeletes,
  });

  @override
  int get hashCode =>
      added.hashCode ^
      updated.hashCode ^
      addedEntries.hashCode ^
      broughtOver.hashCode ^
      pendingDeletes.hashCode ^
      folderConflicts.hashCode ^
      fieldConflicts.hashCode ^
      pendingItemDeletes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergeSummary &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          updated == other.updated &&
          addedEntries == other.addedEntries &&
          broughtOver == other.broughtOver &&
          pendingDeletes == other.pendingDeletes &&
          folderConflicts == other.folderConflicts &&
          fieldConflicts == other.fieldConflicts &&
          pendingItemDeletes == other.pendingItemDeletes;
}

/// A note entry as seen by Flutter.
class NoteEntryData {
  final String id;
  final String createdAt;
  final String updatedAt;
  final String folder;
  final String title;
  final String content;
  final List<CustomFieldData> customFields;

  const NoteEntryData({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.folder,
    required this.title,
    required this.content,
    required this.customFields,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      folder.hashCode ^
      title.hashCode ^
      content.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteEntryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          folder == other.folder &&
          title == other.title &&
          content == other.content &&
          customFields == other.customFields;
}

/// An entry flagged for user-consent deletion during vault merge.
///
/// Returned when an incoming vault contains a tombstone that matches a local
/// entry. Flutter shows a per-entry Delete/Keep dialog before any deletion occurs.
class PendingDeleteItem {
  final String id;
  final String title;

  const PendingDeleteItem({required this.id, required this.title});

  @override
  int get hashCode => id.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingDeleteItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title;
}

/// An item (custom pair / attachment) the incoming side deleted more recently than
/// the local side last changed it. Surfaced as a keep/delete prompt; the item is
/// kept until the user confirms — never silently dropped. `field` is the item key,
/// for example "custom_fields:PIN" (a custom pair) or "attachments:ID" (an attachment).
class PendingItemDeleteItem {
  final String id;
  final String title;
  final String field;

  const PendingItemDeleteItem({
    required this.id,
    required this.title,
    required this.field,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ field.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingItemDeleteItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          field == other.field;
}

/// Set a field/pair on a clash: keep-mine (`keep_incoming` false, `value` ignored)
/// or a dropped brought-over edit (`keep_incoming` true, `value` = value to set).
/// No history is recorded.
class SyncFieldResolutionInput {
  final String id;
  final String field;
  final bool keepIncoming;
  final String value;

  const SyncFieldResolutionInput({
    required this.id,
    required this.field,
    required this.keepIncoming,
    required this.value,
  });

  @override
  int get hashCode =>
      id.hashCode ^ field.hashCode ^ keepIncoming.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncFieldResolutionInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          field == other.field &&
          keepIncoming == other.keepIncoming &&
          value == other.value;
}

/// Assign a chosen folder to an entry (mirrors `session_assign_folder_to_entries`).
class SyncFolderInput {
  final String id;
  final String folder;

  const SyncFolderInput({required this.id, required this.folder});

  @override
  int get hashCode => id.hashCode ^ folder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncFolderInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          folder == other.folder;
}

/// Set `field` to `new_value` and keep `replaced_value` in the entry's history:
/// a kept brought-over edit or a clash resolved to the other device's value.
class SyncHistoryReplacementInput {
  final String id;
  final String field;
  final String newValue;
  final String replacedValue;

  const SyncHistoryReplacementInput({
    required this.id,
    required this.field,
    required this.newValue,
    required this.replacedValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^ field.hashCode ^ newValue.hashCode ^ replacedValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncHistoryReplacementInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          field == other.field &&
          newValue == other.newValue &&
          replacedValue == other.replacedValue;
}

/// Keep or delete an item (custom pair / attachment) the other side removed.
class SyncItemDeleteInput {
  final String id;
  final String field;
  final bool delete;

  const SyncItemDeleteInput({
    required this.id,
    required this.field,
    required this.delete,
  });

  @override
  int get hashCode => id.hashCode ^ field.hashCode ^ delete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncItemDeleteInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          field == other.field &&
          delete == other.delete;
}
