// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'vault.dart';
part 'vault_bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `vault_entry_from_data`, `vault_entry_to_data`

/// Decrypt the vault at `path` and store it in the session.
///
/// Async — Argon2id takes ~667ms on target hardware.
Future<void> unlockVault({
  required List<int> passphrase,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeUnlockVault(
  passphrase: passphrase,
  path: path,
);

/// Drop the session state, locking the vault.
///
/// Sync — instant, no I/O.
void lockVault() => RustLib.instance.api.crateApiVaultBridgeLockVault();

/// Return lightweight summaries of all entries — no secrets.
///
/// Sync — reads from in-memory session, no I/O.
List<EntrySummaryData> listEntrySummaries() =>
    RustLib.instance.api.crateApiVaultBridgeListEntrySummaries();

/// Return the list of folder names from the current session.
///
/// Sync — reads from in-memory session, no I/O.
List<String> listFolders() =>
    RustLib.instance.api.crateApiVaultBridgeListFolders();

/// Rename an existing folder and update all entries that reference it.
///
/// Returns `Err` if `old_name` does not exist, `new_name` is empty,
/// or `new_name` already exists.
/// Async — triggers a full vault save.
Future<void> renameFolder({required String oldName, required String newName}) =>
    RustLib.instance.api.crateApiVaultBridgeRenameFolder(
      oldName: oldName,
      newName: newName,
    );

/// Delete a folder and either reassign its entries to another folder or
/// clear them to unfoldered (`""`).
///
/// Returns `Err` if `name` does not exist, or if `reassign_to` names a
/// folder that does not exist.
/// Async — triggers a full vault save.
Future<void> deleteFolder({required String name, String? reassignTo}) => RustLib
    .instance
    .api
    .crateApiVaultBridgeDeleteFolder(name: name, reassignTo: reassignTo);

/// Add a new folder to the session and persist the vault to disk.
///
/// Returns `Err` if the name is empty or already exists.
/// Async — triggers a full vault save.
Future<void> createFolder({required String name}) =>
    RustLib.instance.api.crateApiVaultBridgeCreateFolder(name: name);

/// Return one full entry DTO by UUID.
///
/// Sync — reads from in-memory session, no I/O.
VaultEntryData getEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultBridgeGetEntry(id: id);

/// Add a new entry to the session and persist the vault to disk.
///
/// Async — triggers a full vault save (Argon2id + encryption).
Future<EntrySummaryData> createEntry({required VaultEntryData entry}) =>
    RustLib.instance.api.crateApiVaultBridgeCreateEntry(entry: entry);

/// Replace an existing entry by UUID and persist.
///
/// `expiry_days`: how long to retain the previous sensitive value.
/// `None` = keep until manually deleted. `Some(n)` = purge after n days.
/// Async — triggers a full vault save.
Future<void> updateEntry({required VaultEntryData entry, int? expiryDays}) =>
    RustLib.instance.api.crateApiVaultBridgeUpdateEntry(
      entry: entry,
      expiryDays: expiryDays,
    );

/// Remove an entry by UUID and persist.
///
/// Async — triggers a full vault save.
Future<void> deleteEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultBridgeDeleteEntry(id: id);

/// Remove multiple entries by UUID in one pass and persist once.
///
/// Async — triggers a single vault save regardless of how many entries
/// are deleted. Use this instead of calling delete_entry in a loop.
Future<void> deleteEntries({required List<String> ids}) =>
    RustLib.instance.api.crateApiVaultBridgeDeleteEntries(ids: ids);

/// Wipe the vault file from disk and drop the session.
///
/// Async — filesystem operation.
Future<void> deleteWholeVault() =>
    RustLib.instance.api.crateApiVaultBridgeDeleteWholeVault();

/// Re-seal the vault under a new passphrase. Session remains live.
///
/// Async — triggers a full vault save.
Future<void> changePassphrase({
  required List<int> oldPassphrase,
  required List<int> newPassphrase,
}) => RustLib.instance.api.crateApiVaultBridgeChangePassphrase(
  oldPassphrase: oldPassphrase,
  newPassphrase: newPassphrase,
);

/// Clear the previous password history for a Login entry and persist.
///
/// Async — triggers a full vault save.
Future<void> sessionClearPasswordHistory({required String id}) =>
    RustLib.instance.api.crateApiVaultBridgeSessionClearPasswordHistory(id: id);

/// Revert the current password to the previous password for a Login entry and persist.
///
/// Async — triggers a full vault save.
Future<void> sessionRevertPassword({required String id}) =>
    RustLib.instance.api.crateApiVaultBridgeSessionRevertPassword(id: id);

/// Assign a folder to a set of entries by UUID and persist.
///
/// Pass `folder: ""` to move entries to unfoldered.
/// Returns `Err` if the folder name does not exist (empty string always valid).
/// Async — triggers a full vault save.
Future<void> assignFolderToEntries({
  required List<String> ids,
  required String folder,
}) => RustLib.instance.api.crateApiVaultBridgeAssignFolderToEntries(
  ids: ids,
  folder: folder,
);

/// Write .gabbro + .gabbro.sha256 from current session state.
///
/// Async — filesystem operation.
Future<void> exportVault({required String path}) =>
    RustLib.instance.api.crateApiVaultBridgeExportVault(path: path);

/// Read the vault header at `path` and return any YubiKey records it contains.
///
/// Does **not** decrypt the vault body — safe to call before the user enters
/// their passphrase. Returns an empty list for passphrase-only vaults.
/// Sync — file I/O + header parse, no crypto.
List<YubikeyRecordData> listVaultYubikeyRecords({required String path}) =>
    RustLib.instance.api.crateApiVaultBridgeListVaultYubikeyRecords(path: path);

/// Decrypt the vault at `path` using both passphrase and YubiKey hmac-secret.
///
/// Handles both VERSION 2 (legacy single-key) and VERSION 3 (multi-key) vaults.
/// For VERSION 3, caches `vault_key_master` in the session so CRUD saves
/// never require a YubiKey re-tap.
///
/// `hmac_secret` must be exactly 32 bytes (FIDO2 hmac-secret output).
/// `hkdf_salt` must be exactly 32 bytes (from `YubikeyRecordData.salt`).
/// Async — Argon2id takes ~667ms on target hardware.
Future<void> unlockVaultWithYubikey({
  required List<int> passphrase,
  required List<int> hmacSecret,
  required List<int> credentialId,
  required List<int> hkdfSalt,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeUnlockVaultWithYubikey(
  passphrase: passphrase,
  hmacSecret: hmacSecret,
  credentialId: credentialId,
  hkdfSalt: hkdfSalt,
  path: path,
);

/// Create a new empty vault at `path`, sealed with `passphrase`.
///
/// Called during onboarding. Async — runs Argon2id + encryption.
Future<void> initVault({required List<int> passphrase, required String path}) =>
    RustLib.instance.api.crateApiVaultBridgeInitVault(
      passphrase: passphrase,
      path: path,
    );

/// Create a new empty vault sealed with a passphrase and two or more YubiKeys.
///
/// Enforces ADR-010: minimum 2 registered keys at vault creation.
/// After creation, unlocks into session immediately using the first key.
/// Async — runs Argon2id + encryption.
Future<void> initVaultWithKeys({
  required List<int> passphrase,
  required List<YubiKeyInitData> keys,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeInitVaultWithKeys(
  passphrase: passphrase,
  keys: keys,
  path: path,
);

/// Create a new empty vault at `path`, sealed with both passphrase and YubiKey.
///
/// Called during onboarding when the user opts in to YubiKey protection.
/// After creation, unlocks into session immediately.
/// `hmac_secret` must be exactly 32 bytes. `hkdf_salt` must be exactly 32 bytes.
/// Async — runs Argon2id + encryption.
Future<void> initVaultWithYubikey({
  required List<int> passphrase,
  required List<int> hmacSecret,
  required List<int> credentialId,
  required List<int> hkdfSalt,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeInitVaultWithYubikey(
  passphrase: passphrase,
  hmacSecret: hmacSecret,
  credentialId: credentialId,
  hkdfSalt: hkdfSalt,
  path: path,
);

/// Return all YubiKey aliases stored in the current session.
///
/// Sync — reads from in-memory session, no I/O.
List<YubikeyAliasData> listYubikeyAliases() =>
    RustLib.instance.api.crateApiVaultBridgeListYubikeyAliases();

/// Set or update the display alias for a registered YubiKey.
///
/// `credential_id_hex` is the hex-encoded credential ID.
/// Async — triggers a full vault body save.
Future<void> setYubikeyAlias({
  required String credentialIdHex,
  required String alias,
}) => RustLib.instance.api.crateApiVaultBridgeSetYubikeyAlias(
  credentialIdHex: credentialIdHex,
  alias: alias,
);

/// Add a new YubiKey to the vault.
///
/// Requires a VERSION 4 vault (wrapping_key must be cached from unlock).
/// Returns `Err` if the vault already has 4 keys or `new_cred_id` is already registered.
/// `new_hmac_secret` and `new_salt` must each be exactly 32 bytes.
/// Async — writes the updated vault header to disk.
Future<void> addYubikey({
  required List<int> newCredId,
  required List<int> newHmacSecret,
  required List<int> newSalt,
}) => RustLib.instance.api.crateApiVaultBridgeAddYubikey(
  newCredId: newCredId,
  newHmacSecret: newHmacSecret,
  newSalt: newSalt,
);

/// Remove a YubiKey from the vault by credential ID.
///
/// Enforces a minimum of 1 remaining key.
/// Async — writes the updated vault header to disk.
Future<void> removeYubikey({required List<int> credId}) =>
    RustLib.instance.api.crateApiVaultBridgeRemoveYubikey(credId: credId);

/// Lightweight entry summary returned by `list_entry_summaries()`.
///
/// Contains just enough for Flutter to render a list row — no secrets.
class EntrySummaryData {
  final String id;
  final String entryType;
  final String title;
  final String folder;

  const EntrySummaryData({
    required this.id,
    required this.entryType,
    required this.title,
    required this.folder,
  });

  @override
  int get hashCode =>
      id.hashCode ^ entryType.hashCode ^ title.hashCode ^ folder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySummaryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryType == other.entryType &&
          title == other.title &&
          folder == other.folder;
}

@freezed
sealed class VaultEntryData with _$VaultEntryData {
  const VaultEntryData._();

  const factory VaultEntryData.login(LoginEntryData field0) =
      VaultEntryData_Login;
  const factory VaultEntryData.note(NoteEntryData field0) = VaultEntryData_Note;
  const factory VaultEntryData.identity(IdentityEntryData field0) =
      VaultEntryData_Identity;
  const factory VaultEntryData.card(CardEntryData field0) = VaultEntryData_Card;
  const factory VaultEntryData.file(FileEntryData field0) = VaultEntryData_File;
  const factory VaultEntryData.custom(CustomEntryData field0) =
      VaultEntryData_Custom;
}

/// Key material for one YubiKey, supplied during multi-key vault creation.
class YubiKeyInitData {
  final Uint8List credentialId;
  final Uint8List hmacSecret;
  final Uint8List hkdfSalt;

  const YubiKeyInitData({
    required this.credentialId,
    required this.hmacSecret,
    required this.hkdfSalt,
  });

  @override
  int get hashCode =>
      credentialId.hashCode ^ hmacSecret.hashCode ^ hkdfSalt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YubiKeyInitData &&
          runtimeType == other.runtimeType &&
          credentialId == other.credentialId &&
          hmacSecret == other.hmacSecret &&
          hkdfSalt == other.hkdfSalt;
}

/// Alias record for one registered YubiKey, returned by `list_yubikey_aliases`.
class YubikeyAliasData {
  /// Hex-encoded credential ID (map key in the vault body).
  final String credentialIdHex;

  /// User-supplied display name; empty string if no alias has been set.
  final String alias;

  const YubikeyAliasData({required this.credentialIdHex, required this.alias});

  @override
  int get hashCode => credentialIdHex.hashCode ^ alias.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YubikeyAliasData &&
          runtimeType == other.runtimeType &&
          credentialIdHex == other.credentialIdHex &&
          alias == other.alias;
}

/// YubiKey credential record returned by `list_vault_yubikey_records`.
///
/// The Android layer uses `credential_id` to identify which YubiKey credential
/// to present, and `salt` as the CTAP2 hmac-secret challenge salt.
class YubikeyRecordData {
  final Uint8List credentialId;
  final Uint8List salt;

  const YubikeyRecordData({required this.credentialId, required this.salt});

  @override
  int get hashCode => credentialId.hashCode ^ salt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YubikeyRecordData &&
          runtimeType == other.runtimeType &&
          credentialId == other.credentialId &&
          salt == other.salt;
}
