// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'vault.dart';
part 'vault_bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `vault_entry_from_data`, `vault_entry_to_data`

/// Serialize, encrypt, and write a vault to disk.
///
/// Called by Flutter with a list of entries, the user's passphrase,
/// and the path to write to. The path is a String because `std::path::Path`
/// is not a bridge-friendly type.
///
/// This is an async function — Flutter awaits it without blocking the UI
/// during the Argon2id KDF (~667ms on target hardware).
Future<void> saveVaultToDisk({
  required List<VaultEntryData> entries,
  required List<int> passphrase,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeSaveVaultToDisk(
  entries: entries,
  passphrase: passphrase,
  path: path,
);

/// Read, decrypt, and deserialize a vault from disk.
///
/// Called by Flutter with the user's passphrase and the path to read from.
/// Returns all entries as bridge-facing DTOs.
///
/// This is an async function — Flutter awaits it without blocking the UI
/// during the Argon2id KDF (~667ms on target hardware).
Future<List<VaultEntryData>> loadVaultFromDisk({
  required List<int> passphrase,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeLoadVaultFromDisk(
  passphrase: passphrase,
  path: path,
);

@freezed
sealed class VaultEntryData with _$VaultEntryData {
  const VaultEntryData._();

  const factory VaultEntryData.login(LoginEntryData field0) =
      VaultEntryData_Login;
  const factory VaultEntryData.note(NoteEntryData field0) = VaultEntryData_Note;
  const factory VaultEntryData.identity(IdentityEntryData field0) =
      VaultEntryData_Identity;
  const factory VaultEntryData.card(CardEntryData field0) = VaultEntryData_Card;
  const factory VaultEntryData.file(FileEntryData field0) = VaultEntryData_File;
  const factory VaultEntryData.custom(CustomEntryData field0) =
      VaultEntryData_Custom;
}
