// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'vault.dart';
part 'vault_bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `vault_entry_from_data`, `vault_entry_to_data`

/// Decrypt the vault at `path` and store it in the session.
///
/// Async — Argon2id takes ~667ms on target hardware.
Future<void> unlockVault({
  required List<int> passphrase,
  required String path,
}) => RustLib.instance.api.crateApiVaultBridgeUnlockVault(
  passphrase: passphrase,
  path: path,
);

/// Drop the session state, locking the vault.
///
/// Sync — instant, no I/O.
void lockVault() => RustLib.instance.api.crateApiVaultBridgeLockVault();

/// Return lightweight summaries of all entries — no secrets.
///
/// Sync — reads from in-memory session, no I/O.
List<EntrySummaryData> listEntrySummaries() =>
    RustLib.instance.api.crateApiVaultBridgeListEntrySummaries();

/// Return one full entry DTO by UUID.
///
/// Sync — reads from in-memory session, no I/O.
VaultEntryData getEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultBridgeGetEntry(id: id);

/// Add a new entry to the session and persist the vault to disk.
///
/// Async — triggers a full vault save (Argon2id + encryption).
Future<EntrySummaryData> createEntry({required VaultEntryData entry}) =>
    RustLib.instance.api.crateApiVaultBridgeCreateEntry(entry: entry);

/// Replace an existing entry by UUID and persist.
///
/// Async — triggers a full vault save.
Future<void> updateEntry({required VaultEntryData entry}) =>
    RustLib.instance.api.crateApiVaultBridgeUpdateEntry(entry: entry);

/// Remove an entry by UUID and persist.
///
/// Async — triggers a full vault save.
Future<void> deleteEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultBridgeDeleteEntry(id: id);

/// Wipe the vault file from disk and drop the session.
///
/// Async — filesystem operation.
Future<void> deleteWholeVault() =>
    RustLib.instance.api.crateApiVaultBridgeDeleteWholeVault();

/// Re-seal the vault under a new passphrase. Session remains live.
///
/// Async — triggers a full vault save.
Future<void> changePassphrase({
  required List<int> oldPassphrase,
  required List<int> newPassphrase,
}) => RustLib.instance.api.crateApiVaultBridgeChangePassphrase(
  oldPassphrase: oldPassphrase,
  newPassphrase: newPassphrase,
);

/// Write .gabbro + .gabbro.sha256 from current session state.
///
/// Async — filesystem operation.
Future<void> exportVault({required String path}) =>
    RustLib.instance.api.crateApiVaultBridgeExportVault(path: path);

/// Create a new empty vault at `path`, sealed with `passphrase`.
///
/// Called during onboarding. Async — runs Argon2id + encryption.
Future<void> initVault({required List<int> passphrase, required String path}) =>
    RustLib.instance.api.crateApiVaultBridgeInitVault(
      passphrase: passphrase,
      path: path,
    );

/// Parse an Enpass JSON export and merge all entries into the live session,
/// then persist the vault to disk.
///
/// `data` is the raw bytes of the Enpass `.json` export file.
/// The vault must already be unlocked — returns `Err` if no session is active.
///
/// Async — triggers a full vault save after import (Argon2id + encryption).
Future<BigInt> importFromEnpass({required List<int> data}) =>
    RustLib.instance.api.crateApiVaultBridgeImportFromEnpass(data: data);

/// Lightweight entry summary returned by `list_entry_summaries()`.
///
/// Contains just enough for Flutter to render a list row — no secrets.
class EntrySummaryData {
  final String id;
  final String entryType;
  final String title;
  final String folder;
  final List<String> tags;
  final bool favourite;

  const EntrySummaryData({
    required this.id,
    required this.entryType,
    required this.title,
    required this.folder,
    required this.tags,
    required this.favourite,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entryType.hashCode ^
      title.hashCode ^
      folder.hashCode ^
      tags.hashCode ^
      favourite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySummaryData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryType == other.entryType &&
          title == other.title &&
          folder == other.folder &&
          tags == other.tags &&
          favourite == other.favourite;
}

@freezed
sealed class VaultEntryData with _$VaultEntryData {
  const VaultEntryData._();

  const factory VaultEntryData.login(LoginEntryData field0) =
      VaultEntryData_Login;
  const factory VaultEntryData.note(NoteEntryData field0) = VaultEntryData_Note;
  const factory VaultEntryData.identity(IdentityEntryData field0) =
      VaultEntryData_Identity;
  const factory VaultEntryData.card(CardEntryData field0) = VaultEntryData_Card;
  const factory VaultEntryData.file(FileEntryData field0) = VaultEntryData_File;
  const factory VaultEntryData.custom(CustomEntryData field0) =
      VaultEntryData_Custom;
}
